// ==============================================================================
// DATOS INICIALES Y GESTOR DE DATOS HOSPITAL PUERTA DE HIERRO (TEPIC)
// ==============================================================================

import {
  UserProfile,
  Patient,
  ScheduledAdmission,
  TriageAdmission,
  ConsultationNote,
  HospitalBed,
  PharmacyItem,
  LabOrder,
  ImagingStudy,
  CashTransaction,
  CeyeBatch,
  ChatMessage,
  AuditLog
} from '../types/hospital';

export const INITIAL_STAFF: UserProfile[] = [
  {
    id: 'usr-admin-alfonso',
    email: 'alfonso.uribe@puertadehierro.com.mx',
    username: 'alfonso.uribe',
    password: 'password123',
    fullName: 'Ing. Alfonso Uribe',
    role: 'ADMINISTRADOR_UNICO',
    professionalLicense: 'ING-DIR-001',
    specialty: 'Dirección General & Sistemas Hospitalarios',
    shift: 'JORNADA_ESPECIAL',
    phone: '311-129-5200',
    isActive: true,
    allowedModules: ['*'],
  },
  {
    id: 'usr-1',
    email: 'carlos.mendoza@puertadehierro.com.mx',
    username: 'carlos.mendoza',
    password: 'password123',
    fullName: 'Dr. Carlos Mendoza Alatorre',
    role: 'DIRECTOR_MEDICO',
    professionalLicense: '4981203',
    specialty: 'Cirugía Cardiovascular',
    shift: 'MATUTINO',
    phone: '311-129-5201',
    isActive: true,
    allowedModules: ['*'],
  },
  {
    id: 'usr-2',
    email: 'sofia.valenzuela@puertadehierro.com.mx',
    username: 'sofia.valenzuela',
    password: 'password123',
    fullName: 'Dra. Sofía Valenzuela Ríos',
    role: 'MEDICO_URGENCIOLOGO',
    professionalLicense: '6789123',
    specialty: 'Urgencias Médico-Quirúrgicas',
    shift: 'MATUTINO',
    phone: '311-129-5206',
    isActive: true,
    allowedModules: ['menu', 'triage', 'hospitalizacion', 'admision_programada', 'consultorios', 'laboratorio', 'rayos_x', 'farmacia', 'chat'],
  },
  {
    id: 'usr-3',
    email: 'fernando.covarrubias@puertadehierro.com.mx',
    username: 'fernando.covarrubias',
    password: 'password123',
    fullName: 'Dr. Fernando Covarrubias',
    role: 'MEDICO_ESPECIALISTA',
    professionalLicense: '5432190',
    specialty: 'Cirugía General y Laparoscopía',
    shift: 'MATUTINO',
    phone: '311-129-5210',
    isActive: true,
    allowedModules: ['menu', 'admision_programada', 'consultorios', 'hospitalizacion', 'chat'],
  },
  {
    id: 'usr-4',
    email: 'mariana.ortega@puertadehierro.com.mx',
    username: 'mariana.ortega',
    password: 'password123',
    fullName: 'Dra. Mariana Ortega Peña',
    role: 'MEDICO_ESPECIALISTA',
    professionalLicense: '7894561',
    specialty: 'Cardiología Intervencionista / Hemodinamia',
    shift: 'MATUTINO',
    phone: '311-129-5215',
    isActive: true,
    allowedModules: ['menu', 'admision_programada', 'consultorios', 'hospitalizacion', 'chat'],
  },
  {
    id: 'usr-5',
    email: 'rocio.barajas@puertadehierro.com.mx',
    username: 'rocio.barajas',
    password: 'password123',
    fullName: 'Enf. Jefa Rocío Barajas',
    role: 'ENFERMERIA_JEFA',
    professionalLicense: '8912345',
    specialty: 'Cuidados Críticos y Terapia Intensiva',
    shift: 'MATUTINO',
    phone: '311-129-5220',
    isActive: true,
    allowedModules: ['menu', 'triage', 'hospitalizacion', 'ceye', 'farmacia', 'chat'],
  },
  {
    id: 'usr-6',
    email: 'roberto.zepeda@puertadehierro.com.mx',
    username: 'roberto.zepeda',
    password: 'password123',
    fullName: 'QFB Roberto Zepeda Orozco',
    role: 'QUIMICO_QFB',
    professionalLicense: '3456789',
    specialty: 'Bioquímica Clínica y Hematología',
    shift: 'MATUTINO',
    phone: '311-129-5230',
    isActive: true,
    allowedModules: ['menu', 'laboratorio', 'chat'],
  },
  {
    id: 'usr-7',
    email: 'javier.santana@puertadehierro.com.mx',
    username: 'javier.santana',
    password: 'password123',
    fullName: 'Dr. Javier Santana Lamas',
    role: 'RADIOLOGO_IMAGEN',
    professionalLicense: '4567890',
    specialty: 'Radiología e Imagen Diagnóstica',
    shift: 'MATUTINO',
    phone: '311-129-5240',
    isActive: true,
    allowedModules: ['menu', 'rayos_x', 'chat'],
  },
  {
    id: 'usr-8',
    email: 'andrea.miramontes@puertadehierro.com.mx',
    username: 'andrea.miramontes',
    password: 'password123',
    fullName: 'Lic. Farm. Andrea Miramontes',
    role: 'FARMACEUTICO',
    professionalLicense: '5678901',
    specialty: 'Farmacia Hospitalaria',
    shift: 'MATUTINO',
    phone: '311-129-5250',
    isActive: true,
    allowedModules: ['menu', 'farmacia', 'chat'],
  },
  {
    id: 'usr-9',
    email: 'patricia.beltran@puertadehierro.com.mx',
    username: 'patricia.beltran',
    password: 'password123',
    fullName: 'Enf. Patricia Beltrán',
    role: 'INSTRUMENTISTA_CEYE',
    professionalLicense: '6789012',
    specialty: 'Esterilización y Quirófanos CEYE',
    shift: 'MATUTINO',
    phone: '311-129-5260',
    isActive: true,
    allowedModules: ['menu', 'ceye', 'chat'],
  },
  {
    id: 'usr-10',
    email: 'gerardo.salcedo@puertadehierro.com.mx',
    username: 'gerardo.salcedo',
    password: 'password123',
    fullName: 'Lic. Gerardo Salcedo',
    role: 'CAJERO_RECEPCION',
    professionalLicense: '7890123',
    specialty: 'Cuentas Hospitalarias y Convenios GMM',
    shift: 'MATUTINO',
    phone: '311-129-5270',
    isActive: true,
    allowedModules: ['menu', 'admision_programada', 'cobro_caja', 'chat'],
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-1',
    patientNumber: 'HPDH-2026-1042',
    curp: 'GOPR580415HNTNR08',
    firstName: 'Roberto',
    lastName: 'González Parra',
    birthDate: '1958-04-15',
    gender: 'MASCULINO',
    bloodType: 'O+',
    allergies: 'Penicilina y derivados betalactámicos',
    chronicConditions: 'Hipertensión Arterial Sistémica, Dislipidemia',
    weightKg: 78.5,
    heightCm: 172.0,
    calculatedBmi: 26.54,
    emergencyContactName: 'Marta González (Esposa)',
    emergencyContactPhone: '311-234-5678',
    insuranceCompany: 'Seguros GNP',
    insurancePolicyNumber: 'GNP-MED-992019-T',
    createdAt: '2026-09-06T08:30:00Z',
  },
  {
    id: 'pat-2',
    patientNumber: 'HPDH-2026-1043',
    curp: 'NAOE840822MNTLR05',
    firstName: 'Elena',
    lastName: 'Navarro Ortiz',
    birthDate: '1984-08-22',
    gender: 'FEMENINO',
    bloodType: 'A+',
    allergies: 'Sulfamidas (Trimetoprima con Sulfametoxazol)',
    chronicConditions: 'Colelitiasis sintomática recurrente',
    weightKg: 64.0,
    heightCm: 160.0,
    calculatedBmi: 25.0,
    emergencyContactName: 'Carlos Ortiz (Hermano)',
    emergencyContactPhone: '311-876-5432',
    insuranceCompany: 'AXA Seguros',
    insurancePolicyNumber: 'AXA-SALUD-883192',
    createdAt: '2026-09-06T11:20:00Z',
  },
  {
    id: 'pat-3',
    patientNumber: 'HPDH-2026-1044',
    curp: 'MOSM020110HNTLM02',
    firstName: 'Mateo',
    lastName: 'Morales Silva',
    birthDate: '2002-01-10',
    gender: 'MASCULINO',
    bloodType: 'B+',
    allergies: 'Ninguna conocida (Negadas)',
    chronicConditions: 'Ninguna',
    weightKg: 70.0,
    heightCm: 178.0,
    calculatedBmi: 22.09,
    emergencyContactName: 'Lucía Silva (Madre)',
    emergencyContactPhone: '311-555-0192',
    insuranceCompany: 'Particular',
    insurancePolicyNumber: 'N/A',
    createdAt: '2026-09-07T06:45:00Z',
  },
  {
    id: 'pat-4',
    patientNumber: 'HPDH-2026-1045',
    curp: 'DOX190518MNTMN01',
    firstName: 'Ximena',
    lastName: 'Domínguez Reyes',
    birthDate: '2019-05-18',
    gender: 'FEMENINO',
    bloodType: 'O+',
    allergies: 'AINEs (Ibuprofeno causa broncoespasmo)',
    chronicConditions: 'Asma bronquial en control',
    weightKg: 22.5,
    heightCm: 118.0,
    calculatedBmi: 16.16,
    emergencyContactName: 'Ernesto Domínguez (Padre)',
    emergencyContactPhone: '311-345-9876',
    insuranceCompany: 'MetLife México',
    insurancePolicyNumber: 'MET-POL-445890',
    createdAt: '2026-09-07T09:10:00Z',
  },
];

// Admisión Hospitalaria Programada (Cirugías, Hemodinamia, Procedimientos)
export const INITIAL_SCHEDULED_ADMISSIONS: ScheduledAdmission[] = [
  {
    id: 'sch-1',
    patientId: 'pat-2',
    patientName: 'Elena Navarro Ortiz',
    patientNumber: 'HPDH-2026-1043',
    admissionType: 'CIRUGIA_PROGRAMADA',
    scheduledDate: '2026-09-08',
    scheduledTime: '08:00',
    procedureName: 'Colecistectomía Laparoscópica Electiva',
    attendingPhysician: 'Dr. Fernando Covarrubias',
    reservedBedArea: 'PISO_2_QUIRURGICO',
    reservedBedNumber: 'P2-204',
    operatingRoomNumber: 'Quirófano 02',
    preanestheticEvaluationCompleted: true,
    fastingConfirmed: true,
    consentFormSigned: true,
    estimatedDurationHours: 2.0,
    status: 'PROGRAMADO',
    notes: 'Ingreso a preparación prequirúrgica a las 07:00 AM. Instrumental de laparoscopía solicitado a CEYE.',
    createdAt: '2026-09-06T12:00:00Z',
  },
  {
    id: 'sch-2',
    patientId: 'pat-1',
    patientName: 'Roberto González Parra',
    patientNumber: 'HPDH-2026-1042',
    admissionType: 'HEMODINAMIA',
    scheduledDate: '2026-09-08',
    scheduledTime: '10:30',
    procedureName: 'Cateterismo Cardíaco y Angioplastia con Stent Farmacoactivo',
    attendingPhysician: 'Dra. Mariana Ortega Peña',
    reservedBedArea: 'UCI_ADULTOS',
    reservedBedNumber: 'UCI-01',
    operatingRoomNumber: 'Sala de Hemodinamia',
    preanestheticEvaluationCompleted: true,
    fastingConfirmed: true,
    consentFormSigned: true,
    estimatedDurationHours: 3.0,
    status: 'PROGRAMADO',
    notes: 'Requiere cama UCI monitorizada post-cateterismo. Tiempos de coagulación y troponinas validadas.',
    createdAt: '2026-09-06T15:30:00Z',
  },
  {
    id: 'sch-3',
    patientId: 'pat-4',
    patientName: 'Ximena Domínguez Reyes',
    patientNumber: 'HPDH-2026-1045',
    admissionType: 'INTERNAMIENTO_ELECTIVO',
    scheduledDate: '2026-09-09',
    scheduledTime: '11:00',
    procedureName: 'Prueba de Función Pulmonar y Ajuste Terapéutico Pediátrico',
    attendingPhysician: 'Dr. Carlos Mendoza Alatorre',
    reservedBedArea: 'PISO_3_HOSPITALIZACION',
    reservedBedNumber: 'P3-305',
    operatingRoomNumber: 'N/A',
    preanestheticEvaluationCompleted: false,
    fastingConfirmed: false,
    consentFormSigned: true,
    estimatedDurationHours: 24.0,
    status: 'PROGRAMADO',
    notes: 'Habitación pediátrica con acompañante permanente.',
    createdAt: '2026-09-07T10:00:00Z',
  },
];

export const INITIAL_TRIAGE: TriageAdmission[] = [
  {
    id: 'trg-1',
    patientId: 'pat-1',
    patientName: 'Roberto González Parra',
    patientNumber: 'HPDH-2026-1042',
    priority: 'ROJO_REANIMACION',
    bloodPressure: '165/95',
    heartRate: 112,
    respiratoryRate: 26,
    temperatureC: 36.8,
    oxygenSaturation: 91,
    bloodGlucose: 154,
    painScaleEva: 9,
    weightKg: 78.5,
    heightCm: 172.0,
    calculatedBmi: 26.54,
    chiefComplaint: 'Dolor torácico retroesternal opresivo irradiado a mandíbula y brazo izquierdo de 45 min de evolución',
    initialDiagnosis: 'Síndrome Coronario Agudo con elevación del ST (Código Infarto)',
    evaluatingPhysician: 'Dra. Sofía Valenzuela Ríos',
    assignedDestination: 'SALA_CHOQUE',
    waitTimeMinutes: 0,
    status: 'EN_ATENCION',
    admissionTimestamp: '2026-09-07T07:15:00Z',
  },
  {
    id: 'trg-2',
    patientId: 'pat-3',
    patientName: 'Mateo Morales Silva',
    patientNumber: 'HPDH-2026-1044',
    priority: 'AMARILLO_URGENCIA',
    bloodPressure: '125/80',
    heartRate: 88,
    respiratoryRate: 18,
    temperatureC: 38.4,
    oxygenSaturation: 98,
    bloodGlucose: 98,
    painScaleEva: 7,
    weightKg: 70.0,
    heightCm: 178.0,
    calculatedBmi: 22.09,
    chiefComplaint: 'Dolor abdominal agudo focalizado en fosa ilíaca derecha (Signo de McBurney positivo), náuseas y febrícula',
    initialDiagnosis: 'Sospecha de Apendicitis Aguda',
    evaluatingPhysician: 'Dra. Sofía Valenzuela Ríos',
    assignedDestination: 'CONSULTORIO_URGENCIAS',
    waitTimeMinutes: 12,
    status: 'EN_ESPERA',
    admissionTimestamp: '2026-09-07T08:00:00Z',
  },
];

export const INITIAL_BEDS: HospitalBed[] = [
  {
    id: 'bed-1',
    bedNumber: 'UCI-01',
    area: 'UCI_ADULTOS',
    status: 'OCUPADA',
    currentPatientId: 'pat-1',
    currentPatientName: 'Roberto González Parra',
    currentPatientNumber: 'HPDH-2026-1042',
    attendingPhysician: 'Dra. Mariana Ortega Peña',
    assignedNurse: 'Enf. Jefa Rocío Barajas',
    admissionDate: '2026-09-07T07:45:00Z',
    dietType: 'Ayuno absoluto (Preparación Hemodinamia)',
    clinicalIsolation: false,
    notes: 'Monitoreo ECG continuo, vía venosa central y O2 por puntas nasales a 3L/min.',
  },
  {
    id: 'bed-2',
    bedNumber: 'UCI-02',
    area: 'UCI_ADULTOS',
    status: 'DISPONIBLE',
    dietType: 'N/A',
    clinicalIsolation: false,
    notes: 'Cama monitorizada con ventilador mecánico calibrado listo.',
  },
  {
    id: 'bed-3',
    bedNumber: 'UCIN-01',
    area: 'UCIN_NEONATAL',
    status: 'OCUPADA',
    dietType: 'Nutrición Parenteral',
    clinicalIsolation: true,
    notes: 'Cuna térmica neonatal de alta tecnología.',
  },
  {
    id: 'bed-4',
    bedNumber: 'UCIN-02',
    area: 'UCIN_NEONATAL',
    status: 'DISPONIBLE',
    dietType: 'N/A',
    clinicalIsolation: false,
  },
  {
    id: 'bed-5',
    bedNumber: 'TERAPIA-01',
    area: 'TERAPIA_INTERMEDIA',
    status: 'DISPONIBLE',
    dietType: 'N/A',
    clinicalIsolation: false,
  },
  {
    id: 'bed-6',
    bedNumber: 'P2-204',
    area: 'PISO_2_QUIRURGICO',
    status: 'DISPONIBLE',
    dietType: 'N/A',
    clinicalIsolation: false,
    notes: 'Reservada para Sra. Elena Navarro (Cirugía programada 08/09).',
  },
  {
    id: 'bed-7',
    bedNumber: 'P2-205',
    area: 'PISO_2_QUIRURGICO',
    status: 'LIMPIEZA_DESINFECCION',
    dietType: 'N/A',
    clinicalIsolation: false,
    notes: 'Terminal de desinfección en proceso.',
  },
  {
    id: 'bed-8',
    bedNumber: 'P3-301',
    area: 'PISO_3_HOSPITALIZACION',
    status: 'OCUPADA',
    dietType: 'Dieta Blanda Hiposódica',
    clinicalIsolation: false,
  },
  {
    id: 'bed-9',
    bedNumber: 'STE-301',
    area: 'SUITES_ESPECIALES',
    status: 'DISPONIBLE',
    dietType: 'N/A',
    clinicalIsolation: false,
    notes: 'Suite Puerta de Hierro con sala de estancia, TV y vista panorámica.',
  },
];

export const INITIAL_PHARMACY: PharmacyItem[] = [
  {
    id: 'ph-1',
    barcode: '7501001100223',
    drugName: 'Propofol 1% Solución Inyectable',
    activeSubstance: 'Propofol 10mg/ml',
    presentation: 'Frasco ámpula con 20ml',
    batchNumber: 'LT-2026-PP88',
    expirationDate: '2027-11-30',
    cofeprisFraction: 'II',
    stockCurrent: 45,
    stockMinimum: 20,
    unitCost: 180.0,
    unitPrice: 380.0,
    locationBin: 'Gabinete Controlados A-1',
    isRefrigerated: false,
  },
  {
    id: 'ph-2',
    barcode: '7501002200334',
    drugName: 'Ceftriaxona 1g Polvo Inyectable',
    activeSubstance: 'Ceftriaxona Sódica 1g',
    presentation: 'Frasco ámpula con diluyente 10ml',
    batchNumber: 'LT-2026-CF12',
    expirationDate: '2028-03-15',
    cofeprisFraction: 'IV',
    stockCurrent: 120,
    stockMinimum: 30,
    unitCost: 65.0,
    unitPrice: 195.0,
    locationBin: 'Estantería B-3',
    isRefrigerated: false,
  },
  {
    id: 'ph-3',
    barcode: '7501003300445',
    drugName: 'Heparina Sódica 5,000 UI/ml',
    activeSubstance: 'Heparina Sódica',
    presentation: 'Frasco ámpula 5ml (25,000 UI)',
    batchNumber: 'LT-2026-HP09',
    expirationDate: '2027-08-20',
    cofeprisFraction: 'IV',
    stockCurrent: 35,
    stockMinimum: 15,
    unitCost: 210.0,
    unitPrice: 480.0,
    locationBin: 'Refrigerador Clínico 02 (4°C)',
    isRefrigerated: true,
  },
  {
    id: 'ph-4',
    barcode: '7501004400556',
    drugName: 'Ketorolaco Trometamina 30mg/ml',
    activeSubstance: 'Ketorolaco',
    presentation: 'Caja con 3 ampolletas de 1ml',
    batchNumber: 'LT-2026-KT44',
    expirationDate: '2027-06-30',
    cofeprisFraction: 'IV',
    stockCurrent: 90,
    stockMinimum: 25,
    unitCost: 45.0,
    unitPrice: 120.0,
    locationBin: 'Estantería A-2',
    isRefrigerated: false,
  },
  {
    id: 'ph-5',
    barcode: '7501005500667',
    drugName: 'Fentanilo 0.5mg/10ml',
    activeSubstance: 'Citrato de Fentanilo',
    presentation: 'Ampolleta 10ml',
    batchNumber: 'LT-2026-FN01',
    expirationDate: '2027-09-15',
    cofeprisFraction: 'I',
    stockCurrent: 18,
    stockMinimum: 10,
    unitCost: 320.0,
    unitPrice: 750.0,
    locationBin: 'Caja Fuerte Narcóticos Quirófano',
    isRefrigerated: false,
  },
];

export const INITIAL_LAB_ORDERS: LabOrder[] = [
  {
    id: 'lab-1',
    orderFolio: 'LAB-2026-0812',
    patientId: 'pat-1',
    patientName: 'Roberto González Parra',
    testName: 'Perfil Cardíaco (Troponina I Alta Sensibilidad, CPK-MB)',
    category: 'BIOQUIMICA',
    priority: 'URGENTE_STAT',
    status: 'VALIDADO_QFB',
    requestingPhysician: 'Dra. Sofía Valenzuela Ríos',
    validatingQfb: 'QFB Roberto Zepeda Orozco',
    validatedAt: '2026-09-07T07:50:00Z',
    criticalAlert: true,
    results: [
      { parameter: 'Troponina I hs', value: '450.2', unit: 'pg/mL', referenceRange: '< 14.0 pg/mL', isAbnormal: true },
      { parameter: 'CPK-MB', value: '68.4', unit: 'U/L', referenceRange: '0.0 - 25.0 U/L', isAbnormal: true },
      { parameter: 'Mioglobina', value: '185.0', unit: 'ng/mL', referenceRange: '28 - 72 ng/mL', isAbnormal: true },
    ],
    createdAt: '2026-09-07T07:20:00Z',
  },
  {
    id: 'lab-2',
    orderFolio: 'LAB-2026-0813',
    patientId: 'pat-3',
    patientName: 'Mateo Morales Silva',
    testName: 'Biometría Hemática Completa con Plaquetas',
    category: 'HEMATOLOGIA',
    priority: 'URGENTE_STAT',
    status: 'EN_ANALISIS',
    requestingPhysician: 'Dr. Fernando Covarrubias',
    criticalAlert: false,
    results: [
      { parameter: 'Leucocitos Totales', value: '16,800', unit: '/mm3', referenceRange: '4,500 - 10,500 /mm3', isAbnormal: true },
      { parameter: 'Neutrófilos', value: '84.0', unit: '%', referenceRange: '45.0 - 70.0 %', isAbnormal: true },
      { parameter: 'Hemoglobina', value: '14.8', unit: 'g/dL', referenceRange: '13.5 - 17.5 g/dL', isAbnormal: false },
      { parameter: 'Plaquetas', value: '240,000', unit: '/mm3', referenceRange: '150,000 - 450,000 /mm3', isAbnormal: false },
    ],
    createdAt: '2026-09-07T08:15:00Z',
  },
];

export const INITIAL_IMAGING: ImagingStudy[] = [
  {
    id: 'img-1',
    studyFolio: 'IMG-2026-0490',
    patientId: 'pat-1',
    patientName: 'Roberto González Parra',
    modality: 'HEMODINAMIA',
    bodyPart: 'Coronariografía diagnóstica y terapéutica',
    clinicalIndication: 'Infarto agudo de miocardio con elevación del ST (IAMCEST anterior extenso)',
    radiologistInterpretation: 'Oclusión crítica del 95% en tercio proximal de la Arteria Descendente Anterior (DA). Éxito en colocación de Stent farmacoactivo con flujo TIMI 3 recuperado.',
    radiologistName: 'Dra. Mariana Ortega Peña',
    radiologistLicense: '7894561',
    status: 'INTERPRETADO_FIRMADO',
    createdAt: '2026-09-07T08:00:00Z',
  },
  {
    id: 'img-2',
    studyFolio: 'IMG-2026-0491',
    patientId: 'pat-3',
    patientName: 'Mateo Morales Silva',
    modality: 'TOMOGRAFIA_TC',
    bodyPart: 'TC Simple y Contrastada de Abdomen y Pelvis',
    clinicalIndication: 'Sospecha clínica de apendicitis aguda grado II',
    radiologistInterpretation: 'Apendice cecal engrosado con diámetro de 11 mm, estriación de la grasa periapendicular y coprolito visible en la base. Hallazgos compatibles con apendicitis aguda sin perforación evidente.',
    radiologistName: 'Dr. Javier Santana Lamas',
    radiologistLicense: '4567890',
    status: 'INTERPRETADO_FIRMADO',
    createdAt: '2026-09-07T08:45:00Z',
  },
];

export const INITIAL_CEYE: CeyeBatch[] = [
  {
    id: 'ceye-1',
    batchCode: 'CEYE-2026-0941',
    autoclaveName: 'Autoclave Matachana Vapor 01',
    sterilizationMethod: 'VAPOR_134',
    cycleNumber: 3,
    temperatureC: 134.5,
    pressurePsi: 32.0,
    durationMinutes: 45,
    chemicalIndicatorApproved: true,
    biologicalIndicatorApproved: true,
    sterileExpirationDate: '2026-10-07',
    packageDescription: 'Set Instrumental Cirugía Mayor No. 04 + Paquete de Ropa Quirúrgica',
    destinationArea: 'Quirófano 01 (Cirugía Cardiovascular)',
    responsibleTechnician: 'Enf. Patricia Beltrán',
    status: 'LIBERADO_ESTERIL',
    createdAt: '2026-09-07T06:30:00Z',
  },
  {
    id: 'ceye-2',
    batchCode: 'CEYE-2026-0942',
    autoclaveName: 'Sterrad NX Plasma Gas 02',
    sterilizationMethod: 'PLASMA_GAS',
    cycleNumber: 2,
    temperatureC: 55.0,
    pressurePsi: 15.0,
    durationMinutes: 42,
    chemicalIndicatorApproved: true,
    biologicalIndicatorApproved: true,
    sterileExpirationDate: '2026-12-07',
    packageDescription: 'Óptica Karl Storz 30° 10mm + Set Pinzas Laparoscópicas Bipolares',
    destinationArea: 'Quirófano 02 (Laparoscopía - Paciente Elena Navarro)',
    responsibleTechnician: 'Enf. Patricia Beltrán',
    status: 'LIBERADO_ESTERIL',
    createdAt: '2026-09-07T07:15:00Z',
  },
];

export const INITIAL_TRANSACTIONS: CashTransaction[] = [
  {
    id: 'caj-1',
    receiptNumber: 'CAJA-2026-0512',
    patientId: 'pat-1',
    patientName: 'Roberto González Parra',
    serviceCategory: 'QUIROFANO',
    conceptDescription: 'Procedimiento de Hemodinamia, Angioplastia Coronaria y Stent Medicado',
    subtotal: 145000.0,
    taxAmount: 0.0,
    totalAmount: 145000.0,
    insuranceCoverageAmount: 130500.0, // Cobertura 90% GNP
    patientCopayAmount: 14500.0,       // Deducible / Coaseguro 10%
    paymentMethod: 'ASEGURADORA_CONVENIO',
    cashierName: 'Lic. Gerardo Salcedo',
    shift: 'MATUTINO',
    status: 'PAGADO',
    createdAt: '2026-09-07T09:30:00Z',
  },
  {
    id: 'caj-2',
    receiptNumber: 'CAJA-2026-0513',
    patientId: 'pat-3',
    patientName: 'Mateo Morales Silva',
    serviceCategory: 'LABORATORIO',
    conceptDescription: 'Biometría Hemática, Química 36 y Tiempos de Coagulación Urgentes',
    subtotal: 3200.0,
    taxAmount: 0.0,
    totalAmount: 3200.0,
    insuranceCoverageAmount: 0.0,
    patientCopayAmount: 3200.0,
    paymentMethod: 'TARJETA_DEBITO',
    cashierName: 'Lic. Gerardo Salcedo',
    shift: 'MATUTINO',
    status: 'PAGADO',
    createdAt: '2026-09-07T08:50:00Z',
  },
];

export const INITIAL_CHAT: ChatMessage[] = [
  {
    id: 'msg-1',
    channelName: 'URGENCIAS_TRIAGE',
    senderId: 'usr-2',
    senderName: 'Dra. Sofía Valenzuela Ríos',
    senderRole: 'MEDICO_URGENCIOLOGO',
    messageText: '🚨 CÓDIGO INFARTO ACTIVADO en Sala de Choque. Paciente masculino 68 años (Don Roberto). Troponinas positivas 450 pg/mL.',
    attachmentType: 'ALERTA_VITAL',
    isRead: true,
    timestamp: '07:35 AM',
  },
  {
    id: 'msg-2',
    channelName: 'URGENCIAS_TRIAGE',
    senderId: 'usr-4',
    senderName: 'Dra. Mariana Ortega Peña',
    senderRole: 'MEDICO_ESPECIALISTA',
    messageText: 'Recibido Dra. Valenzuela. Sala de hemodinamia lista. Suban al paciente de inmediato.',
    isRead: true,
    timestamp: '07:37 AM',
  },
  {
    id: 'msg-3',
    channelName: 'QUIROFANOS_CEYE',
    senderId: 'usr-3',
    senderName: 'Dr. Fernando Covarrubias',
    senderRole: 'MEDICO_ESPECIALISTA',
    messageText: 'Buenos días CEYE. Confirmar si la torre de laparoscopía y set de colecistectomía para la Sra. Elena Navarro ya tienen indicadores aprobados.',
    isRead: true,
    timestamp: '08:10 AM',
  },
  {
    id: 'msg-4',
    channelName: 'QUIROFANOS_CEYE',
    senderId: 'usr-9',
    senderName: 'Enf. Patricia Beltrán',
    senderRole: 'INSTRUMENTISTA_CEYE',
    messageText: 'Afirmativo Dr. Covarrubias, lote CEYE-2026-0942 liberado y estéril en Quirófano 02.',
    isRead: true,
    timestamp: '08:12 AM',
  },
  {
    id: 'msg-5',
    channelName: 'GUARDIA_MEDICA',
    senderId: 'usr-1',
    senderName: 'Dr. Carlos Mendoza Alatorre',
    senderRole: 'DIRECTOR_MEDICO',
    messageText: 'Equipo Puerta de Hierro Tepic: Se recuerda registrar peso, talla y notas completas en cada admisión bajo estricta norma NOM-004 y NOM-024.',
    isRead: true,
    timestamp: '08:30 AM',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-1',
    timestamp: '2026-09-07T07:15:22Z',
    userName: 'Dra. Sofía Valenzuela Ríos',
    userRole: 'MEDICO_URGENCIOLOGO',
    userLicense: '6789123',
    ipAddress: '192.168.1.45 (Red Hospitalaria Tepic)',
    actionType: 'INGRESO_TRIAGE_MANCHESTER',
    resourceAffected: 'Expediente HPDH-2026-1042',
    details: 'Clasificación Rojo Reanimación. Signos vitales capturados con peso 78.5kg y talla 172cm.',
    sha256Hash: 'a9f8e3c7b2d1e045f8a6c7b9e0123456789abcdef0123456789abcdef0123456',
  },
  {
    id: 'aud-2',
    timestamp: '2026-09-07T07:50:11Z',
    userName: 'QFB Roberto Zepeda Orozco',
    userRole: 'QUIMICO_QFB',
    userLicense: '3456789',
    ipAddress: '192.168.1.78 (Laboratorio Clínico 24H)',
    actionType: 'VALIDACION_ANALITICA_LABORATORIO',
    resourceAffected: 'Folio LAB-2026-0812',
    details: 'Validación de Troponina hs y CPK-MB con alerta de valores críticos bajo NOM-007.',
    sha256Hash: 'b8e7d2c1a0f9e834c7b6a5d4e3f2109876543210fedcba9876543210fedcba98',
  },
];
