// ==============================================================================
// DATOS INICIALES Y GESTOR DE DATOS HOSPITAL PUERTA DE HIERRO (TEPIC)
// ==============================================================================

import {
  UserProfile,
  Patient,
  ScheduledAdmission,
  TriageAdmission,
  ConsultationNote,
  HospitalBed,
  PharmacyItem,
  LabOrder,
  ImagingStudy,
  CashTransaction,
  CeyeBatch,
  ChatMessage,
  AuditLog,
  WarehouseItem,
  WarehouseDispatch,
  Supplier,
  PurchaseOrder,
  PurchaseRequisition,
  SocialWorkRecord
} from '../types/hospital';

export const INITIAL_STAFF: UserProfile[] = [
  {
    id: 'usr-admin-alfonso',
    email: 'alfonso.uribe@puertadehierro.com.mx',
    username: 'alfonso.uribe',
    password: 'password123',
    fullName: 'Ing. Alfonso Uribe',
    role: 'ADMINISTRADOR_UNICO',
    professionalLicense: 'ING-DIR-001',
    specialty: 'Dirección General & Sistemas Hospitalarios',
    shift: 'JORNADA_ESPECIAL',
    phone: '311-129-5200',
    isActive: true,
    allowedModules: ['*'],
  },
  {
    id: 'usr-1',
    email: 'carlos.mendoza@puertadehierro.com.mx',
    username: 'carlos.mendoza',
    password: 'password123',
    fullName: 'Dr. Carlos Mendoza Alatorre',
    role: 'DIRECTOR_MEDICO',
    professionalLicense: '4981203',
    specialty: 'Cirugía Cardiovascular',
    shift: 'MATUTINO',
    phone: '311-129-5201',
    isActive: true,
    allowedModules: ['*'],
  },
  {
    id: 'usr-2',
    email: 'sofia.valenzuela@puertadehierro.com.mx',
    username: 'sofia.valenzuela',
    password: 'password123',
    fullName: 'Dra. Sofía Valenzuela Ríos',
    role: 'MEDICO_URGENCIOLOGO',
    professionalLicense: '6789123',
    specialty: 'Urgencias Médico-Quirúrgicas',
    shift: 'MATUTINO',
    phone: '311-129-5206',
    isActive: true,
    allowedModules: ['menu', 'triage', 'hospitalizacion', 'admision_programada', 'consultorios', 'laboratorio', 'rayos_x', 'farmacia', 'chat'],
  },
  {
    id: 'usr-3',
    email: 'fernando.covarrubias@puertadehierro.com.mx',
    username: 'fernando.covarrubias',
    password: 'password123',
    fullName: 'Dr. Fernando Covarrubias',
    role: 'MEDICO_ESPECIALISTA',
    professionalLicense: '5432190',
    specialty: 'Cirugía General y Laparoscopía',
    shift: 'MATUTINO',
    phone: '311-129-5210',
    isActive: true,
    allowedModules: ['menu', 'admision_programada', 'consultorios', 'hospitalizacion', 'chat'],
  },
  {
    id: 'usr-4',
    email: 'mariana.ortega@puertadehierro.com.mx',
    username: 'mariana.ortega',
    password: 'password123',
    fullName: 'Dra. Mariana Ortega Peña',
    role: 'MEDICO_ESPECIALISTA',
    professionalLicense: '7894561',
    specialty: 'Cardiología Intervencionista / Hemodinamia',
    shift: 'MATUTINO',
    phone: '311-129-5215',
    isActive: true,
    allowedModules: ['menu', 'admision_programada', 'consultorios', 'hospitalizacion', 'chat'],
  },
  {
    id: 'usr-5',
    email: 'rocio.barajas@puertadehierro.com.mx',
    username: 'rocio.barajas',
    password: 'password123',
    fullName: 'Enf. Jefa Rocío Barajas',
    role: 'ENFERMERIA_JEFA',
    professionalLicense: '8912345',
    specialty: 'Cuidados Críticos y Terapia Intensiva',
    shift: 'MATUTINO',
    phone: '311-129-5220',
    isActive: true,
    allowedModules: ['menu', 'triage', 'hospitalizacion', 'ceye', 'farmacia', 'chat'],
  },
  {
    id: 'usr-6',
    email: 'roberto.zepeda@puertadehierro.com.mx',
    username: 'roberto.zepeda',
    password: 'password123',
    fullName: 'QFB Roberto Zepeda Orozco',
    role: 'QUIMICO_QFB',
    professionalLicense: '3456789',
    specialty: 'Bioquímica Clínica y Hematología',
    shift: 'MATUTINO',
    phone: '311-129-5230',
    isActive: true,
    allowedModules: ['menu', 'laboratorio', 'chat'],
  },
  {
    id: 'usr-7',
    email: 'javier.santana@puertadehierro.com.mx',
    username: 'javier.santana',
    password: 'password123',
    fullName: 'Dr. Javier Santana Lamas',
    role: 'RADIOLOGO_IMAGEN',
    professionalLicense: '4567890',
    specialty: 'Radiología e Imagen Diagnóstica',
    shift: 'MATUTINO',
    phone: '311-129-5240',
    isActive: true,
    allowedModules: ['menu', 'rayos_x', 'chat'],
  },
  {
    id: 'usr-8',
    email: 'andrea.miramontes@puertadehierro.com.mx',
    username: 'andrea.miramontes',
    password: 'password123',
    fullName: 'Lic. Farm. Andrea Miramontes',
    role: 'FARMACEUTICO',
    professionalLicense: '5678901',
    specialty: 'Farmacia Hospitalaria',
    shift: 'MATUTINO',
    phone: '311-129-5250',
    isActive: true,
    allowedModules: ['menu', 'farmacia', 'chat'],
  },
  {
    id: 'usr-9',
    email: 'patricia.beltran@puertadehierro.com.mx',
    username: 'patricia.beltran',
    password: 'password123',
    fullName: 'Enf. Patricia Beltrán',
    role: 'INSTRUMENTISTA_CEYE',
    professionalLicense: '6789012',
    specialty: 'Esterilización y Quirófanos CEYE',
    shift: 'MATUTINO',
    phone: '311-129-5260',
    isActive: true,
    allowedModules: ['menu', 'ceye', 'chat'],
  },
  {
    id: 'usr-10',
    email: 'gerardo.salcedo@puertadehierro.com.mx',
    username: 'gerardo.salcedo',
    password: 'password123',
    fullName: 'Lic. Gerardo Salcedo',
    role: 'CAJERO_RECEPCION',
    professionalLicense: '7890123',
    specialty: 'Cuentas Hospitalarias y Convenios GMM',
    shift: 'MATUTINO',
    phone: '311-129-5270',
    isActive: true,
    allowedModules: ['menu', 'admision_programada', 'cobro_caja', 'chat'],
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'pat-1',
    patientNumber: 'HPDH-2026-1042',
    curp: 'GOPR580415HNTNR08',
    firstName: 'Roberto',
    lastName: 'González Parra',
    birthDate: '1958-04-15',
    gender: 'MASCULINO',
    bloodType: 'O+',
    allergies: 'Penicilina y derivados betalactámicos (Shock anafiláctico)',
    chronicConditions: 'Hipertensión Arterial Sistémica, Dislipidemia mixta',
    weightKg: 78.5,
    heightCm: 172.0,
    calculatedBmi: 26.54,
    emergencyContactName: 'Marta González (Esposa)',
    emergencyContactPhone: '311-234-5678',
    insuranceCompany: 'Seguros GNP',
    insurancePolicyNumber: 'GNP-MED-992019-T',
    vaccinationHistory: [
      'COVID-19 (Esquema Bivalente 2024)',
      'Influenza Estacional 2025-2026 (Aplicada)',
      'Tétanos / Tdpa (Refuerzo 2022)',
      'Neumococo 23-valente (Dosis única)'
    ],
    familyHistory: 'Padre finado por Infarto Agudo al Miocardio a los 58 años. Madre con Diabetes Mellitus Tipo 2 e Hipertensión.',
    pathologicalHistory: 'Hipertensión Arterial de 14 años de diagnóstico en tratamiento. Apendicectomía abierta a los 24 años. Niega transfusiones.',
    createdAt: '2026-09-06T08:30:00Z',
  },
  {
    id: 'pat-2',
    patientNumber: 'HPDH-2026-1043',
    curp: 'NAOE840822MNTLR05',
    firstName: 'Elena',
    lastName: 'Navarro Ortiz',
    birthDate: '1984-08-22',
    gender: 'FEMENINO',
    bloodType: 'A+',
    allergies: 'Sulfamidas (Trimetoprima con Sulfametoxazol - Exantema generalizado)',
    chronicConditions: 'Colelitiasis sintomática recurrente',
    weightKg: 64.0,
    heightCm: 160.0,
    calculatedBmi: 25.0,
    emergencyContactName: 'Carlos Ortiz (Hermano)',
    emergencyContactPhone: '311-876-5432',
    insuranceCompany: 'AXA Seguros',
    insurancePolicyNumber: 'AXA-SALUD-883192',
    vaccinationHistory: [
      'COVID-19 (3 Dosis completas)',
      'Influenza Estacional 2025-2026',
      'Hepatitis B (3 dosis)',
      'VPH (Esquema completo)'
    ],
    familyHistory: 'Madre viva con Colecistectomía previa y Litiasis Vesicular. Tía materna con Ca de Mama.',
    pathologicalHistory: 'Colelitiasis litiásica sintomática de 8 meses. Cesárea previa hace 6 años sin complicaciones.',
    createdAt: '2026-09-06T11:20:00Z',
  },
  {
    id: 'pat-3',
    patientNumber: 'HPDH-2026-1044',
    curp: 'MOSM020110HNTLM02',
    firstName: 'Mateo',
    lastName: 'Morales Silva',
    birthDate: '2002-01-10',
    gender: 'MASCULINO',
    bloodType: 'B+',
    allergies: 'Ninguna conocida (Negadas)',
    chronicConditions: 'Ninguna',
    weightKg: 70.0,
    heightCm: 178.0,
    calculatedBmi: 22.09,
    emergencyContactName: 'Lucía Silva (Madre)',
    emergencyContactPhone: '311-555-0192',
    insuranceCompany: 'Particular',
    insurancePolicyNumber: 'N/A',
    vaccinationHistory: [
      'COVID-19 (2 Dosis)',
      'Tétanos / Td (Refuerzo 2024)',
      'Hepatitis B (Esquema completo infantil)'
    ],
    familyHistory: 'Sin antecedentes crónico-degenerativos de primer grado.',
    pathologicalHistory: 'Amigdalectomía a los 8 años. Sin hospitalizaciones previas.',
    createdAt: '2026-09-07T06:45:00Z',
  },
  {
    id: 'pat-4',
    patientNumber: 'HPDH-2026-1045',
    curp: 'DOX190518MNTMN01',
    firstName: 'Ximena',
    lastName: 'Domínguez Reyes',
    birthDate: '2019-05-18',
    gender: 'FEMENINO',
    bloodType: 'O+',
    allergies: 'AINEs (Ibuprofeno causa broncoespasmo severo)',
    chronicConditions: 'Asma bronquial alérgica en control',
    weightKg: 22.5,
    heightCm: 118.0,
    calculatedBmi: 16.16,
    emergencyContactName: 'Ernesto Domínguez (Padre)',
    emergencyContactPhone: '311-345-9876',
    insuranceCompany: 'MetLife México',
    insurancePolicyNumber: 'MET-POL-445890',
    vaccinationHistory: [
      'Cartilla Nacional de Vacunación al Corriente',
      'SRP (Sarampión, Rubeola, Parotiditis - 2 Dosis)',
      'Hexavalente Acelular (4 Dosis)',
      'Neumococo Conjugada (3 Dosis)',
      'Varicela (1 Dosis)',
      'Influenza Pediátrica Anual'
    ],
    familyHistory: 'Padre con Rinitis Alérgica y Asma en la infancia. Madre sana.',
    pathologicalHistory: 'Asma bronquial diagnosticada a los 3 años. Sin eventos de intubación orotraqueal.',
    createdAt: '2026-09-07T09:10:00Z',
  },
];

// Admisión Hospitalaria Programada (Cirugías, Hemodinamia, Procedimientos)
export const INITIAL_SCHEDULED_ADMISSIONS: ScheduledAdmission[] = [
  {
    id: 'sch-1',
    patientId: 'pat-2',
    patientName: 'Elena Navarro Ortiz',
    patientNumber: 'HPDH-2026-1043',
    admissionType: 'CIRUGIA_PROGRAMADA',
    scheduledDate: '2026-09-08',
    scheduledTime: '08:00',
    procedureName: 'Colecistectomía Laparoscópica Electiva',
    attendingPhysician: 'Dr. Fernando Covarrubias',
    reservedBedArea: 'PISO_2_QUIRURGICO',
    reservedBedNumber: 'P2-204',
    operatingRoomNumber: 'Quirófano 02',
    preanestheticEvaluationCompleted: true,
    fastingConfirmed: true,
    consentFormSigned: true,
    estimatedDurationHours: 2.0,
    status: 'PROGRAMADO',
    notes: 'Ingreso a preparación prequirúrgica a las 07:00 AM. Instrumental de laparoscopía solicitado a CEYE.',
    createdAt: '2026-09-06T12:00:00Z',
  },
  {
    id: 'sch-2',
    patientId: 'pat-1',
    patientName: 'Roberto González Parra',
    patientNumber: 'HPDH-2026-1042',
    admissionType: 'HEMODINAMIA',
    scheduledDate: '2026-09-08',
    scheduledTime: '10:30',
    procedureName: 'Cateterismo Cardíaco y Angioplastia con Stent Farmacoactivo',
    attendingPhysician: 'Dra. Mariana Ortega Peña',
    reservedBedArea: 'UCI_ADULTOS',
    reservedBedNumber: 'UCI-01',
    operatingRoomNumber: 'Sala de Hemodinamia',
    preanestheticEvaluationCompleted: true,
    fastingConfirmed: true,
    consentFormSigned: true,
    estimatedDurationHours: 3.0,
    status: 'PROGRAMADO',
    notes: 'Requiere cama UCI monitorizada post-cateterismo. Tiempos de coagulación y troponinas validadas.',
    createdAt: '2026-09-06T15:30:00Z',
  },
  {
    id: 'sch-3',
    patientId: 'pat-4',
    patientName: 'Ximena Domínguez Reyes',
    patientNumber: 'HPDH-2026-1045',
    admissionType: 'INTERNAMIENTO_ELECTIVO',
    scheduledDate: '2026-09-09',
    scheduledTime: '11:00',
    procedureName: 'Prueba de Función Pulmonar y Ajuste Terapéutico Pediátrico',
    attendingPhysician: 'Dr. Carlos Mendoza Alatorre',
    reservedBedArea: 'PISO_3_HOSPITALIZACION',
    reservedBedNumber: 'P3-305',
    operatingRoomNumber: 'N/A',
    preanestheticEvaluationCompleted: false,
    fastingConfirmed: false,
    consentFormSigned: true,
    estimatedDurationHours: 24.0,
    status: 'PROGRAMADO',
    notes: 'Habitación pediátrica con acompañante permanente.',
    createdAt: '2026-09-07T10:00:00Z',
  },
];

export const INITIAL_TRIAGE: TriageAdmission[] = [
  {
    id: 'trg-1',
    patientId: 'pat-1',
    patientName: 'Roberto González Parra',
    patientNumber: 'HPDH-2026-1042',
    priority: 'ROJO_REANIMACION',
    bloodPressure: '165/95',
    heartRate: 112,
    respiratoryRate: 26,
    temperatureC: 36.8,
    oxygenSaturation: 91,
    bloodGlucose: 154,
    painScaleEva: 9,
    weightKg: 78.5,
    heightCm: 172.0,
    calculatedBmi: 26.54,
    chiefComplaint: 'Dolor torácico retroesternal opresivo irradiado a mandíbula y brazo izquierdo de 45 min de evolución',
    initialDiagnosis: 'Síndrome Coronario Agudo con elevación del ST (Código Infarto)',
    evaluatingPhysician: 'Dra. Sofía Valenzuela Ríos',
    assignedDestination: 'SALA_CHOQUE',
    waitTimeMinutes: 0,
    status: 'EN_ATENCION',
    admissionTimestamp: '2026-09-07T07:15:00Z',
  },
  {
    id: 'trg-2',
    patientId: 'pat-3',
    patientName: 'Mateo Morales Silva',
    patientNumber: 'HPDH-2026-1044',
    priority: 'AMARILLO_URGENCIA',
    bloodPressure: '125/80',
    heartRate: 88,
    respiratoryRate: 18,
    temperatureC: 38.4,
    oxygenSaturation: 98,
    bloodGlucose: 98,
    painScaleEva: 7,
    weightKg: 70.0,
    heightCm: 178.0,
    calculatedBmi: 22.09,
    chiefComplaint: 'Dolor abdominal agudo focalizado en fosa ilíaca derecha (Signo de McBurney positivo), náuseas y febrícula',
    initialDiagnosis: 'Sospecha de Apendicitis Aguda',
    evaluatingPhysician: 'Dra. Sofía Valenzuela Ríos',
    assignedDestination: 'CONSULTORIO_URGENCIAS',
    waitTimeMinutes: 12,
    status: 'EN_ESPERA',
    admissionTimestamp: '2026-09-07T08:00:00Z',
  },
  {
    id: 'trg-3',
    patientId: 'pat-2',
    patientName: 'Elena Navarro Ortiz',
    patientNumber: 'HPDH-2026-1043',
    priority: 'AMARILLO_URGENCIA',
    bloodPressure: '118/76',
    heartRate: 76,
    respiratoryRate: 16,
    temperatureC: 36.9,
    oxygenSaturation: 98,
    bloodGlucose: 92,
    painScaleEva: 6,
    weightKg: 64.0,
    heightCm: 160.0,
    calculatedBmi: 25.0,
    chiefComplaint: 'Dolor cólico en hipocondrio derecho posprandial tras ingesta de grasas colecistoquinéticas, náusea leve.',
    initialDiagnosis: 'Colecistitis litiásica sintomática / Protocolo prequirúrgico',
    evaluatingPhysician: 'Dr. Fernando Covarrubias',
    assignedDestination: 'CONSULTORIO_URGENCIAS',
    waitTimeMinutes: 10,
    status: 'EN_ATENCION',
    admissionTimestamp: '2026-09-07T08:30:00Z',
  },
  {
    id: 'trg-4',
    patientId: 'pat-4',
    patientName: 'Ximena Domínguez Reyes',
    patientNumber: 'HPDH-2026-1045',
    priority: 'VERDE_MENOR',
    bloodPressure: '95/60',
    heartRate: 92,
    respiratoryRate: 22,
    temperatureC: 36.6,
    oxygenSaturation: 97,
    bloodGlucose: 88,
    painScaleEva: 3,
    weightKg: 22.5,
    heightCm: 118.0,
    calculatedBmi: 16.16,
    chiefComplaint: 'Tos nocturna seca ocasional y sibilancias leves con ejercicio moderado. Consulta de control pediátrico.',
    initialDiagnosis: 'Asma bronquial alérgica pediátrica en control',
    evaluatingPhysician: 'Dra. Sofía Valenzuela Ríos',
    assignedDestination: 'CONSULTORIO_URGENCIAS',
    waitTimeMinutes: 5,
    status: 'EN_ESPERA',
    admissionTimestamp: '2026-09-07T09:15:00Z',
  },
];

export const INITIAL_BEDS: HospitalBed[] = [
  {
    id: 'bed-1',
    bedNumber: 'UCI-01',
    area: 'UCI_ADULTOS',
    status: 'OCUPADA',
    currentPatientId: 'pat-1',
    currentPatientName: 'Roberto González Parra',
    currentPatientNumber: 'HPDH-2026-1042',
    attendingPhysician: 'Dra. Mariana Ortega Peña',
    assignedNurse: 'Enf. Jefa Rocío Barajas',
    admissionDate: '2026-09-07T07:45:00Z',
    dietType: 'Ayuno absoluto (Preparación Hemodinamia)',
    clinicalIsolation: false,
    notes: 'Monitoreo ECG continuo, vía venosa central y O2 por puntas nasales a 3L/min.',
  },
  {
    id: 'bed-2',
    bedNumber: 'UCI-02',
    area: 'UCI_ADULTOS',
    status: 'DISPONIBLE',
    dietType: 'N/A',
    clinicalIsolation: false,
    notes: 'Cama monitorizada con ventilador mecánico calibrado listo.',
  },
  {
    id: 'bed-3',
    bedNumber: 'UCIN-01',
    area: 'UCIN_NEONATAL',
    status: 'OCUPADA',
    dietType: 'Nutrición Parenteral',
    clinicalIsolation: true,
    notes: 'Cuna térmica neonatal de alta tecnología.',
  },
  {
    id: 'bed-4',
    bedNumber: 'UCIN-02',
    area: 'UCIN_NEONATAL',
    status: 'DISPONIBLE',
    dietType: 'N/A',
    clinicalIsolation: false,
  },
  {
    id: 'bed-5',
    bedNumber: 'TERAPIA-01',
    area: 'TERAPIA_INTERMEDIA',
    status: 'DISPONIBLE',
    dietType: 'N/A',
    clinicalIsolation: false,
  },
  {
    id: 'bed-6',
    bedNumber: 'P2-204',
    area: 'PISO_2_QUIRURGICO',
    status: 'DISPONIBLE',
    dietType: 'N/A',
    clinicalIsolation: false,
    notes: 'Reservada para Sra. Elena Navarro (Cirugía programada 08/09).',
  },
  {
    id: 'bed-7',
    bedNumber: 'P2-205',
    area: 'PISO_2_QUIRURGICO',
    status: 'LIMPIEZA_DESINFECCION',
    dietType: 'N/A',
    clinicalIsolation: false,
    notes: 'Terminal de desinfección en proceso.',
  },
  {
    id: 'bed-8',
    bedNumber: 'P3-301',
    area: 'PISO_3_HOSPITALIZACION',
    status: 'OCUPADA',
    dietType: 'Dieta Blanda Hiposódica',
    clinicalIsolation: false,
  },
  {
    id: 'bed-9',
    bedNumber: 'STE-301',
    area: 'SUITES_ESPECIALES',
    status: 'DISPONIBLE',
    dietType: 'N/A',
    clinicalIsolation: false,
    notes: 'Suite Puerta de Hierro con sala de estancia, TV y vista panorámica.',
  },
];

export const INITIAL_PHARMACY: PharmacyItem[] = [
  {
    id: 'ph-1',
    barcode: '7501001100223',
    drugName: 'Propofol 1% Solución Inyectable',
    activeSubstance: 'Propofol 10mg/ml',
    presentation: 'Frasco ámpula con 20ml',
    batchNumber: 'LT-2026-PP88',
    expirationDate: '2027-11-30',
    cofeprisFraction: 'II',
    stockCurrent: 45,
    stockMinimum: 20,
    unitCost: 180.0,
    unitPrice: 380.0,
    locationBin: 'Gabinete Controlados A-1',
    isRefrigerated: false,
  },
  {
    id: 'ph-2',
    barcode: '7501002200334',
    drugName: 'Ceftriaxona 1g Polvo Inyectable',
    activeSubstance: 'Ceftriaxona Sódica 1g',
    presentation: 'Frasco ámpula con diluyente 10ml',
    batchNumber: 'LT-2026-CF12',
    expirationDate: '2028-03-15',
    cofeprisFraction: 'IV',
    stockCurrent: 120,
    stockMinimum: 30,
    unitCost: 65.0,
    unitPrice: 195.0,
    locationBin: 'Estantería B-3',
    isRefrigerated: false,
  },
  {
    id: 'ph-3',
    barcode: '7501003300445',
    drugName: 'Heparina Sódica 5,000 UI/ml',
    activeSubstance: 'Heparina Sódica',
    presentation: 'Frasco ámpula 5ml (25,000 UI)',
    batchNumber: 'LT-2026-HP09',
    expirationDate: '2027-08-20',
    cofeprisFraction: 'IV',
    stockCurrent: 35,
    stockMinimum: 15,
    unitCost: 210.0,
    unitPrice: 480.0,
    locationBin: 'Refrigerador Clínico 02 (4°C)',
    isRefrigerated: true,
  },
  {
    id: 'ph-4',
    barcode: '7501004400556',
    drugName: 'Ketorolaco Trometamina 30mg/ml',
    activeSubstance: 'Ketorolaco',
    presentation: 'Caja con 3 ampolletas de 1ml',
    batchNumber: 'LT-2026-KT44',
    expirationDate: '2027-06-30',
    cofeprisFraction: 'IV',
    stockCurrent: 90,
    stockMinimum: 25,
    unitCost: 45.0,
    unitPrice: 120.0,
    locationBin: 'Estantería A-2',
    isRefrigerated: false,
  },
  {
    id: 'ph-5',
    barcode: '7501005500667',
    drugName: 'Fentanilo 0.5mg/10ml',
    activeSubstance: 'Citrato de Fentanilo',
    presentation: 'Ampolleta 10ml',
    batchNumber: 'LT-2026-FN01',
    expirationDate: '2027-09-15',
    cofeprisFraction: 'I',
    stockCurrent: 18,
    stockMinimum: 10,
    unitCost: 320.0,
    unitPrice: 750.0,
    locationBin: 'Caja Fuerte Narcóticos Quirófano',
    isRefrigerated: false,
  },
];

export const INITIAL_LAB_ORDERS: LabOrder[] = [
  {
    id: 'lab-1',
    orderFolio: 'LAB-2026-0812',
    patientId: 'pat-1',
    patientName: 'Roberto González Parra',
    testName: 'Perfil Cardíaco (Troponina I Alta Sensibilidad, CPK-MB)',
    category: 'BIOQUIMICA',
    priority: 'URGENTE_STAT',
    status: 'VALIDADO_QFB',
    requestingPhysician: 'Dra. Sofía Valenzuela Ríos',
    validatingQfb: 'QFB Roberto Zepeda Orozco',
    validatedAt: '2026-09-07T07:50:00Z',
    criticalAlert: true,
    results: [
      { parameter: 'Troponina I hs', value: '450.2', unit: 'pg/mL', referenceRange: '< 14.0 pg/mL', isAbnormal: true },
      { parameter: 'CPK-MB', value: '68.4', unit: 'U/L', referenceRange: '0.0 - 25.0 U/L', isAbnormal: true },
      { parameter: 'Mioglobina', value: '185.0', unit: 'ng/mL', referenceRange: '28 - 72 ng/mL', isAbnormal: true },
    ],
    createdAt: '2026-09-07T07:20:00Z',
  },
  {
    id: 'lab-2',
    orderFolio: 'LAB-2026-0813',
    patientId: 'pat-3',
    patientName: 'Mateo Morales Silva',
    testName: 'Biometría Hemática Completa con Plaquetas',
    category: 'HEMATOLOGIA',
    priority: 'URGENTE_STAT',
    status: 'EN_ANALISIS',
    requestingPhysician: 'Dr. Fernando Covarrubias',
    criticalAlert: false,
    results: [
      { parameter: 'Leucocitos Totales', value: '16,800', unit: '/mm3', referenceRange: '4,500 - 10,500 /mm3', isAbnormal: true },
      { parameter: 'Neutrófilos', value: '84.0', unit: '%', referenceRange: '45.0 - 70.0 %', isAbnormal: true },
      { parameter: 'Hemoglobina', value: '14.8', unit: 'g/dL', referenceRange: '13.5 - 17.5 g/dL', isAbnormal: false },
      { parameter: 'Plaquetas', value: '240,000', unit: '/mm3', referenceRange: '150,000 - 450,000 /mm3', isAbnormal: false },
    ],
    createdAt: '2026-09-07T08:15:00Z',
  },
];

export const INITIAL_IMAGING: ImagingStudy[] = [
  {
    id: 'img-1',
    studyFolio: 'IMG-2026-0490',
    patientId: 'pat-1',
    patientName: 'Roberto González Parra',
    modality: 'HEMODINAMIA',
    bodyPart: 'Coronariografía diagnóstica y terapéutica',
    clinicalIndication: 'Infarto agudo de miocardio con elevación del ST (IAMCEST anterior extenso)',
    radiologistInterpretation: 'Oclusión crítica del 95% en tercio proximal de la Arteria Descendente Anterior (DA). Éxito en colocación de Stent farmacoactivo con flujo TIMI 3 recuperado.',
    radiologistName: 'Dra. Mariana Ortega Peña',
    radiologistLicense: '7894561',
    status: 'INTERPRETADO_FIRMADO',
    createdAt: '2026-09-07T08:00:00Z',
  },
  {
    id: 'img-2',
    studyFolio: 'IMG-2026-0491',
    patientId: 'pat-3',
    patientName: 'Mateo Morales Silva',
    modality: 'TOMOGRAFIA_TC',
    bodyPart: 'TC Simple y Contrastada de Abdomen y Pelvis',
    clinicalIndication: 'Sospecha clínica de apendicitis aguda grado II',
    radiologistInterpretation: 'Apendice cecal engrosado con diámetro de 11 mm, estriación de la grasa periapendicular y coprolito visible en la base. Hallazgos compatibles con apendicitis aguda sin perforación evidente.',
    radiologistName: 'Dr. Javier Santana Lamas',
    radiologistLicense: '4567890',
    status: 'INTERPRETADO_FIRMADO',
    createdAt: '2026-09-07T08:45:00Z',
  },
];

export const INITIAL_CEYE: CeyeBatch[] = [
  {
    id: 'ceye-1',
    batchCode: 'CEYE-2026-0941',
    autoclaveName: 'Autoclave Matachana Vapor 01',
    sterilizationMethod: 'VAPOR_134',
    cycleNumber: 3,
    temperatureC: 134.5,
    pressurePsi: 32.0,
    durationMinutes: 45,
    chemicalIndicatorApproved: true,
    biologicalIndicatorApproved: true,
    sterileExpirationDate: '2026-10-07',
    packageDescription: 'Set Instrumental Cirugía Mayor No. 04 + Paquete de Ropa Quirúrgica',
    destinationArea: 'Quirófano 01 (Cirugía Cardiovascular)',
    responsibleTechnician: 'Enf. Patricia Beltrán',
    status: 'LIBERADO_ESTERIL',
    createdAt: '2026-09-07T06:30:00Z',
  },
  {
    id: 'ceye-2',
    batchCode: 'CEYE-2026-0942',
    autoclaveName: 'Sterrad NX Plasma Gas 02',
    sterilizationMethod: 'PLASMA_GAS',
    cycleNumber: 2,
    temperatureC: 55.0,
    pressurePsi: 15.0,
    durationMinutes: 42,
    chemicalIndicatorApproved: true,
    biologicalIndicatorApproved: true,
    sterileExpirationDate: '2026-12-07',
    packageDescription: 'Óptica Karl Storz 30° 10mm + Set Pinzas Laparoscópicas Bipolares',
    destinationArea: 'Quirófano 02 (Laparoscopía - Paciente Elena Navarro)',
    responsibleTechnician: 'Enf. Patricia Beltrán',
    status: 'LIBERADO_ESTERIL',
    createdAt: '2026-09-07T07:15:00Z',
  },
];

export const INITIAL_TRANSACTIONS: CashTransaction[] = [
  {
    id: 'caj-1',
    receiptNumber: 'CAJA-2026-0512',
    patientId: 'pat-1',
    patientName: 'Roberto González Parra',
    serviceCategory: 'QUIROFANO',
    conceptDescription: 'Procedimiento de Hemodinamia, Angioplastia Coronaria y Stent Medicado',
    subtotal: 145000.0,
    taxCategory: 'EXENTO_MEDICO',
    taxRate: 0.0,
    taxAmount: 0.0,
    totalAmount: 145000.0,
    insuranceCoverageAmount: 130500.0, // Cobertura 90% GNP
    patientCopayAmount: 14500.0,       // Deducible / Coaseguro 10%
    paymentMethod: 'ASEGURADORA_CONVENIO',
    insuranceAgreement: {
      companyName: 'GNP Seguros',
      companyRfc: 'GNP9211244Z0',
      companyBusinessName: 'GRUPO NACIONAL PROVINCIAL S.A.B.',
      policyNumber: 'GNP-GMM-0091823',
      claimNumber: 'SIN-2026-44120',
      authorizationCode: 'AUT-GNP-2026-9812',
      creditDaysTerms: 30,
      invoiceTarget: 'ASEGURADORA',
    },
    cashierName: 'Lic. Gerardo Salcedo',
    shift: 'MATUTINO',
    status: 'FACTURADO',
    isInvoiceIssued: true,
    invoiceData: {
      invoiceFolio: 'CFDI-2026-0812',
      uuidSat: '4E4766EB-11B0-427E-8E8D-9081C817BEFC',
      rfcRecipient: 'GNP9211244Z0',
      businessName: 'GRUPO NACIONAL PROVINCIAL S.A.B.',
      taxRegime: '601 - General de Ley Personas Morales',
      postalCode: '04200',
      cfdiUsage: 'G03 - Gastos en general',
      paymentMethodSat: 'PPD - Pago en parcialidades o diferido',
      paymentFormSat: '99 - Por definir',
      satCertificateNumber: '00001000000504465028',
      emisorCertificateNumber: '00001000000506148821',
      satDigitalStamp: 'T3xY9kL2m...SAT_STAMP_VERIFIED_DIGITAL',
      cfdiDigitalStamp: 'dGhpcyBpcyBhIHZhbGlkIGNmZGkgc3RhbXA=',
      originalStringSat: '||1.1|4E4766EB-11B0-427E-8E8D-9081C817BEFC|2026-09-07T09:35:00|SAT970701NN3|145000.00||',
      timbradoDate: '2026-09-07T09:35:00',
      cfdiStatus: 'TIMBRADA_SAT'
    },
    createdAt: '2026-09-07T09:30:00Z',
  },
  {
    id: 'caj-2',
    receiptNumber: 'CAJA-2026-0513',
    patientId: 'pat-3',
    patientName: 'Mateo Morales Silva',
    serviceCategory: 'LABORATORIO',
    conceptDescription: 'Biometría Hemática, Química 36 y Tiempos de Coagulación Urgentes',
    subtotal: 3200.0,
    taxCategory: 'EXENTO_MEDICO',
    taxRate: 0.0,
    taxAmount: 0.0,
    totalAmount: 3200.0,
    insuranceCoverageAmount: 0.0,
    patientCopayAmount: 3200.0,
    paymentMethod: 'TARJETA_DEBITO',
    cashierName: 'Lic. Gerardo Salcedo',
    shift: 'MATUTINO',
    status: 'PAGADO',
    isInvoiceIssued: false,
    createdAt: '2026-09-07T08:50:00Z',
  },
  {
    id: 'caj-3',
    receiptNumber: 'CAJA-2026-0514',
    patientId: 'pat-2',
    patientName: 'Elena Navarro Ortiz',
    serviceCategory: 'FARMACIA',
    conceptDescription: 'Material de Osteosíntesis, Gasas Estériles y Soluciones Intravenosas Especiales',
    subtotal: 12500.0,
    taxCategory: 'IVA_16',
    taxRate: 0.16,
    taxAmount: 2000.0,
    totalAmount: 14500.0,
    insuranceCoverageAmount: 11600.0, // 80% AXA
    patientCopayAmount: 2900.0,
    paymentMethod: 'TARJETA_CREDITO',
    insuranceAgreement: {
      companyName: 'AXA Seguros',
      companyRfc: 'AXA9704288A9',
      companyBusinessName: 'AXA SEGUROS S.A. DE C.V.',
      policyNumber: 'AXA-SALUD-883192',
      claimNumber: 'SIN-AXA-2026-1029',
      authorizationCode: 'AUT-AXA-2026-7731',
      creditDaysTerms: 30,
      invoiceTarget: 'PACIENTE_COPAGO',
    },
    cashierName: 'Lic. Gerardo Salcedo',
    shift: 'MATUTINO',
    status: 'FACTURADO',
    isInvoiceIssued: true,
    invoiceData: {
      invoiceFolio: 'CFDI-2026-0813',
      uuidSat: '8F23A1B9-4C5D-6E7F-8A90-123456789ABC',
      rfcRecipient: 'NAOE840822HP4',
      businessName: 'ELENA NAVARRO ORTIZ',
      taxRegime: '605 - Sueldos y Salarios e Ingresos Asimilados',
      postalCode: '63000',
      cfdiUsage: 'D01 - Honorarios médicos, dentales y gastos hospitalarios',
      paymentMethodSat: 'PUE - Pago en una sola exhibición',
      paymentFormSat: '04 - Tarjeta de crédito',
      satCertificateNumber: '00001000000504465028',
      emisorCertificateNumber: '00001000000506148821',
      satDigitalStamp: 'K8sP2xQ9m...SAT_STAMP_FARMACIA_IVA16',
      cfdiDigitalStamp: 'eG1sX2Zhcm1hY2lhX2l2YV8xNg==',
      originalStringSat: '||1.1|8F23A1B9-4C5D-6E7F-8A90-123456789ABC|2026-09-07T10:15:00|SAT970701NN3|12500.00|2000.00||',
      timbradoDate: '2026-09-07T10:15:00',
      cfdiStatus: 'TIMBRADA_SAT'
    },
    createdAt: '2026-09-07T10:10:00Z',
  },
  {
    id: 'caj-4',
    receiptNumber: 'CAJA-2026-0515',
    patientId: 'pat-4',
    patientName: 'Ximena Domínguez Reyes',
    serviceCategory: 'HOSPITALIZACION',
    conceptDescription: 'Día Estancia Pediátrica Monitorizada y Terapia Respiratoria Asistida',
    subtotal: 18000.0,
    taxCategory: 'EXENTO_MEDICO',
    taxRate: 0.0,
    taxAmount: 0.0,
    totalAmount: 18000.0,
    insuranceCoverageAmount: 16200.0,
    patientCopayAmount: 1800.0,
    paymentMethod: 'ASEGURADORA_CONVENIO',
    insuranceAgreement: {
      companyName: 'MetLife México',
      companyRfc: 'MMX010918V56',
      companyBusinessName: 'METLIFE MÉXICO S.A. DE C.V.',
      policyNumber: 'MET-POL-445890',
      claimNumber: 'SIN-MET-2026-0992',
      authorizationCode: 'AUT-MET-2026-3391',
      creditDaysTerms: 45,
      invoiceTarget: 'ASEGURADORA',
    },
    cashierName: 'Lic. Gerardo Salcedo',
    shift: 'MATUTINO',
    status: 'PAGADO',
    isInvoiceIssued: false,
    createdAt: '2026-09-07T11:40:00Z',
  },
  {
    id: 'caj-5',
    receiptNumber: 'CAJA-2026-0516',
    patientId: 'pat-3',
    patientName: 'Mateo Morales Silva',
    serviceCategory: 'IMAGENOLOGIA',
    conceptDescription: 'Tomografía Computarizada Craneal Simple y Contraste Iónico',
    subtotal: 6500.0,
    taxCategory: 'EXENTO_MEDICO',
    taxRate: 0.0,
    taxAmount: 0.0,
    totalAmount: 6500.0,
    insuranceCoverageAmount: 0.0,
    patientCopayAmount: 6500.0,
    paymentMethod: 'TRANSFERENCIA_SPEI',
    cashierName: 'Lic. Gerardo Salcedo',
    shift: 'MATUTINO',
    status: 'PAGADO',
    isInvoiceIssued: false,
    createdAt: '2026-09-07T12:05:00Z',
  },
];

export const INITIAL_CHAT: ChatMessage[] = [
  {
    id: 'msg-1',
    channelName: 'URGENCIAS_TRIAGE',
    senderId: 'usr-2',
    senderName: 'Dra. Sofía Valenzuela Ríos',
    senderRole: 'MEDICO_URGENCIOLOGO',
    messageText: '🚨 CÓDIGO INFARTO ACTIVADO en Sala de Choque. Paciente masculino 68 años (Don Roberto). Troponinas positivas 450 pg/mL.',
    attachmentType: 'ALERTA_VITAL',
    isRead: true,
    timestamp: '07:35 AM',
  },
  {
    id: 'msg-2',
    channelName: 'URGENCIAS_TRIAGE',
    senderId: 'usr-4',
    senderName: 'Dra. Mariana Ortega Peña',
    senderRole: 'MEDICO_ESPECIALISTA',
    messageText: 'Recibido Dra. Valenzuela. Sala de hemodinamia lista. Suban al paciente de inmediato.',
    isRead: true,
    timestamp: '07:37 AM',
  },
  {
    id: 'msg-3',
    channelName: 'QUIROFANOS_CEYE',
    senderId: 'usr-3',
    senderName: 'Dr. Fernando Covarrubias',
    senderRole: 'MEDICO_ESPECIALISTA',
    messageText: 'Buenos días CEYE. Confirmar si la torre de laparoscopía y set de colecistectomía para la Sra. Elena Navarro ya tienen indicadores aprobados.',
    isRead: true,
    timestamp: '08:10 AM',
  },
  {
    id: 'msg-4',
    channelName: 'QUIROFANOS_CEYE',
    senderId: 'usr-9',
    senderName: 'Enf. Patricia Beltrán',
    senderRole: 'INSTRUMENTISTA_CEYE',
    messageText: 'Afirmativo Dr. Covarrubias, lote CEYE-2026-0942 liberado y estéril en Quirófano 02.',
    isRead: true,
    timestamp: '08:12 AM',
  },
  {
    id: 'msg-5',
    channelName: 'GUARDIA_MEDICA',
    senderId: 'usr-1',
    senderName: 'Dr. Carlos Mendoza Alatorre',
    senderRole: 'DIRECTOR_MEDICO',
    messageText: 'Equipo Puerta de Hierro Tepic: Se recuerda registrar peso, talla y notas completas en cada admisión bajo estricta norma NOM-004 y NOM-024.',
    isRead: true,
    timestamp: '08:30 AM',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-login-1',
    timestamp: '2026-09-08T08:00:15Z',
    userName: 'Ing. Alfonso Uribe',
    userRole: 'ADMINISTRADOR_UNICO',
    userLicense: 'ING-DIR-001',
    ipAddress: '192.168.1.10 (Dirección General Tepic)',
    actionType: 'INICIO_SESION_EXITOSO',
    resourceAffected: 'Portal de Acceso Hospitalario',
    details: 'Autenticación exitosa de Administrador Único. Acceso total autorizado a los 14 módulos hospitalarios.',
    sha256Hash: '9c5f8e3c7b2d1e045f8a6c7b9e0123456789abcdef0123456789abcdef0123456',
  },
  {
    id: 'aud-login-2',
    timestamp: '2026-09-08T08:15:30Z',
    userName: 'Dr. Carlos Mendoza Alatorre',
    userRole: 'DIRECTOR_MEDICO',
    userLicense: '4981203',
    ipAddress: '192.168.1.12 (Jefatura Médica)',
    actionType: 'INICIO_SESION_EXITOSO',
    resourceAffected: 'Portal de Acceso Hospitalario',
    details: 'Autenticación exitosa con credenciales biométricas y clave. Acceso concedido a estación clínica.',
    sha256Hash: '8b7e2c1a0f9e834c7b6a5d4e3f2109876543210fedcba9876543210fedcba98a',
  },
  {
    id: 'aud-1',
    timestamp: '2026-09-07T07:15:22Z',
    userName: 'Dra. Sofía Valenzuela Ríos',
    userRole: 'MEDICO_URGENCIOLOGO',
    userLicense: '6789123',
    ipAddress: '192.168.1.45 (Red Hospitalaria Tepic)',
    actionType: 'INGRESO_TRIAGE_MANCHESTER',
    resourceAffected: 'Expediente HPDH-2026-1042',
    details: 'Clasificación Rojo Reanimación. Signos vitales capturados con peso 78.5kg y talla 172cm.',
    sha256Hash: 'a9f8e3c7b2d1e045f8a6c7b9e0123456789abcdef0123456789abcdef0123456',
  },
  {
    id: 'aud-2',
    timestamp: '2026-09-07T07:50:11Z',
    userName: 'QFB Roberto Zepeda Orozco',
    userRole: 'QUIMICO_QFB',
    userLicense: '3456789',
    ipAddress: '192.168.1.78 (Laboratorio Clínico 24H)',
    actionType: 'VALIDACION_ANALITICA_LABORATORIO',
    resourceAffected: 'Folio LAB-2026-0812',
    details: 'Validación de Troponina hs y CPK-MB con alerta de valores críticos bajo NOM-007.',
    sha256Hash: 'b8e7d2c1a0f9e834c7b6a5d4e3f2109876543210fedcba9876543210fedcba98',
  },
];

// ==============================================================================
// MÓDULO 13: ALMACÉN GENERAL DE INSUMOS HOSPITALARIOS
// ==============================================================================

export const INITIAL_WAREHOUSE_ITEMS: WarehouseItem[] = [
  {
    id: 'alm-1',
    sku: 'ALM-CUR-001',
    itemName: 'Catéter Intravenoso Periférico BD Insyte 18G Verde',
    category: 'MATERIAL_CURACION',
    unit: 'CAJA',
    stockCurrent: 145,
    stockMinimum: 50,
    stockMaximum: 300,
    locationRack: 'Pasillo A - Estante 1 - Nivel 2',
    unitCost: 485.00,
    lastRestockDate: '2026-09-02',
    batchNumber: 'L-2026-BD18',
    expirationDate: '2028-12-31',
    notes: 'Insumo de alta rotación para Quirófanos y Urgencias (Caja c/50 pzas)'
  },
  {
    id: 'alm-2',
    sku: 'ALM-CUR-002',
    itemName: 'Catéter Intravenoso Periférico BD Insyte 20G Rosa',
    category: 'MATERIAL_CURACION',
    unit: 'CAJA',
    stockCurrent: 120,
    stockMinimum: 50,
    stockMaximum: 300,
    locationRack: 'Pasillo A - Estante 1 - Nivel 2',
    unitCost: 485.00,
    lastRestockDate: '2026-09-02',
    batchNumber: 'L-2026-BD20',
    expirationDate: '2028-11-30',
    notes: 'Caja c/50 pzas'
  },
  {
    id: 'alm-3',
    sku: 'ALM-CUR-003',
    itemName: 'Jeringa Desechable BD Plastipak 5ml c/Aguja 21G',
    category: 'MATERIAL_CURACION',
    unit: 'CAJA',
    stockCurrent: 85,
    stockMinimum: 40,
    stockMaximum: 200,
    locationRack: 'Pasillo A - Estante 2 - Nivel 1',
    unitCost: 320.00,
    lastRestockDate: '2026-08-28',
    batchNumber: 'L-2026-PL5',
    expirationDate: '2029-05-31',
    notes: 'Caja c/100 pzas con pivote Luer-Lok'
  },
  {
    id: 'alm-4',
    sku: 'ALM-CUR-004',
    itemName: 'Gasas Estériles Hartmann 10x10 cm c/Trama Radiopaca',
    category: 'MATERIAL_CURACION',
    unit: 'PAQUETE',
    stockCurrent: 32,
    stockMinimum: 20,
    stockMaximum: 100,
    locationRack: 'Pasillo B - Estante 1 - Nivel 3',
    unitCost: 265.00,
    lastRestockDate: '2026-08-30',
    batchNumber: 'L-2026-H10',
    expirationDate: '2029-03-31',
    notes: 'Paquete con 200 gasas para uso quirúrgico'
  },
  {
    id: 'alm-5',
    sku: 'ALM-CUR-005',
    itemName: 'Sutura Vicryl 3-0 Absorbible Trenzada Aguja SH 26mm',
    category: 'MATERIAL_CURACION',
    unit: 'CAJA',
    stockCurrent: 18,
    stockMinimum: 15,
    stockMaximum: 50,
    locationRack: 'Pasillo B - Estante 3 - Nivel 1',
    unitCost: 1420.00,
    lastRestockDate: '2026-08-20',
    batchNumber: 'L-2026-V30',
    expirationDate: '2028-09-30',
    notes: 'Caja c/36 sobres para Cirugía General y Gineco'
  },
  {
    id: 'alm-6',
    sku: 'ALM-CUR-006',
    itemName: 'Apósito Transparente 3M Tegaderm Film 10x12 cm',
    category: 'MATERIAL_CURACION',
    unit: 'CAJA',
    stockCurrent: 8,
    stockMinimum: 15,
    stockMaximum: 60,
    locationRack: 'Pasillo A - Estante 3 - Nivel 2',
    unitCost: 890.00,
    lastRestockDate: '2026-08-15',
    batchNumber: 'L-2026-TG10',
    expirationDate: '2028-04-30',
    notes: '⚠️ NIVEL CRÍTICO: Reabastecimiento urgente para UCI y Terapia'
  },
  {
    id: 'alm-7',
    sku: 'ALM-SOL-001',
    itemName: 'Solución Cloruro de Sodio 0.9% Fisiológica 1000ml Baxter',
    category: 'SOLUCIONES_PARENTERALES',
    unit: 'CAJA',
    stockCurrent: 65,
    stockMinimum: 30,
    stockMaximum: 150,
    locationRack: 'Pasillo C - Estante 1 - Nivel 1',
    unitCost: 340.00,
    lastRestockDate: '2026-09-01',
    batchNumber: 'L-2026-CS1K',
    expirationDate: '2028-10-31',
    notes: 'Caja c/12 bolsas Viaflex libres de PVC'
  },
  {
    id: 'alm-8',
    sku: 'ALM-SOL-002',
    itemName: 'Solución Hartmann Electrolitos Balanceados 1000ml Baxter',
    category: 'SOLUCIONES_PARENTERALES',
    unit: 'CAJA',
    stockCurrent: 52,
    stockMinimum: 25,
    stockMaximum: 120,
    locationRack: 'Pasillo C - Estante 1 - Nivel 2',
    unitCost: 365.00,
    lastRestockDate: '2026-09-01',
    batchNumber: 'L-2026-HM1K',
    expirationDate: '2028-11-30',
    notes: 'Caja c/12 bolsas Viaflex para reposición hidroelectrolítica'
  },
  {
    id: 'alm-9',
    sku: 'ALM-SOL-003',
    itemName: 'Solución Glucosada al 5% 500ml Baxter',
    category: 'SOLUCIONES_PARENTERALES',
    unit: 'CAJA',
    stockCurrent: 14,
    stockMinimum: 20,
    stockMaximum: 80,
    locationRack: 'Pasillo C - Estante 2 - Nivel 1',
    unitCost: 310.00,
    lastRestockDate: '2026-08-18',
    batchNumber: 'L-2026-GL500',
    expirationDate: '2028-08-31',
    notes: '⚠️ Requiere requisición a compras'
  },
  {
    id: 'alm-10',
    sku: 'ALM-PRO-001',
    itemName: 'Guantes Quirúrgicos Estériles de Látex Sin Polvo 7.5',
    category: 'EQUIPO_PROTECCION',
    unit: 'CAJA',
    stockCurrent: 110,
    stockMinimum: 40,
    stockMaximum: 250,
    locationRack: 'Pasillo D - Estante 1 - Nivel 2',
    unitCost: 780.00,
    lastRestockDate: '2026-09-03',
    batchNumber: 'L-2026-GQ75',
    expirationDate: '2029-01-31',
    notes: 'Caja c/50 pares estériles empaque individual'
  },
  {
    id: 'alm-11',
    sku: 'ALM-PRO-002',
    itemName: 'Mascarilla Quirúrgica Respirador N95 3M 1860',
    category: 'EQUIPO_PROTECCION',
    unit: 'CAJA',
    stockCurrent: 45,
    stockMinimum: 20,
    stockMaximum: 100,
    locationRack: 'Pasillo D - Estante 2 - Nivel 1',
    unitCost: 520.00,
    lastRestockDate: '2026-08-25',
    batchNumber: 'L-2026-3M95',
    expirationDate: '2030-12-31',
    notes: 'Caja c/20 piezas aprobadas NIOSH para áreas críticas'
  },
  {
    id: 'alm-12',
    sku: 'ALM-ROP-001',
    itemName: 'Bata Quirúrgica Desechable Reforzada Estéril Talla XL',
    category: 'ROPERIA_LENCERIA',
    unit: 'PAQUETE',
    stockCurrent: 35,
    stockMinimum: 15,
    stockMaximum: 80,
    locationRack: 'Pasillo E - Estante 1 - Nivel 1',
    unitCost: 1150.00,
    lastRestockDate: '2026-08-29',
    batchNumber: 'L-2026-BQXL',
    expirationDate: '2029-08-31',
    notes: 'Paquete con 25 batas de alta protección hidrorepelente'
  },
  {
    id: 'alm-13',
    sku: 'ALM-REC-001',
    itemName: 'Tubos Vacutainer BD Tapa Lila EDTA K2 4ml',
    category: 'REACTIVOS_INSUMOS',
    unit: 'PAQUETE',
    stockCurrent: 28,
    stockMinimum: 15,
    stockMaximum: 60,
    locationRack: 'Pasillo F - Estante 1 - Nivel 2',
    unitCost: 410.00,
    lastRestockDate: '2026-08-27',
    batchNumber: 'L-2026-EDTA',
    expirationDate: '2028-06-30',
    notes: 'Gradilla c/100 tubos para Biometría Hemática'
  }
];

export const INITIAL_WAREHOUSE_DISPATCHES: WarehouseDispatch[] = [
  {
    id: 'val-1',
    dispatchFolio: 'VALE-2026-0182',
    requestingDepartment: 'QUIROFANOS',
    requestedBy: 'Dr. Fernando Covarrubias',
    deliveredBy: 'T.S. Gabriel Montes (Almacén)',
    dispatchedDate: '2026-09-08 07:45',
    status: 'ENTREGADO',
    items: [
      { itemId: 'alm-8', itemName: 'Solución Hartmann 1000ml', sku: 'ALM-SOL-002', quantity: 4 },
      { itemId: 'alm-5', itemName: 'Sutura Vicryl 3-0', sku: 'ALM-CUR-005', quantity: 2 },
      { itemId: 'alm-12', itemName: 'Bata Quirúrgica Reforzada XL', sku: 'ALM-ROP-001', quantity: 2 }
    ],
    notes: 'Suministro para Programación Quirúrgica Matutina'
  },
  {
    id: 'val-2',
    dispatchFolio: 'VALE-2026-0183',
    requestingDepartment: 'URGENCIAS',
    requestedBy: 'Dra. Sofía Valenzuela Ríos',
    deliveredBy: 'T.S. Gabriel Montes (Almacén)',
    dispatchedDate: '2026-09-08 08:15',
    status: 'ENTREGADO',
    items: [
      { itemId: 'alm-1', itemName: 'Catéter Periférico 18G Verde', sku: 'ALM-CUR-001', quantity: 3 },
      { itemId: 'alm-7', itemName: 'Solución Fisiológica 0.9% 1000ml', sku: 'ALM-SOL-001', quantity: 5 },
      { itemId: 'alm-3', itemName: 'Jeringa Plastipak 5ml', sku: 'ALM-CUR-003', quantity: 3 }
    ],
    notes: 'Dotación de Sala de Choque y Observación'
  },
  {
    id: 'val-3',
    dispatchFolio: 'VALE-2026-0184',
    requestingDepartment: 'UCI_ADULTOS',
    requestedBy: 'Enf. Jefa Rocío Barajas',
    deliveredBy: 'T.S. Gabriel Montes (Almacén)',
    dispatchedDate: '2026-09-08 08:40',
    status: 'ENTREGADO',
    items: [
      { itemId: 'alm-6', itemName: 'Apósito Tegaderm 10x12', sku: 'ALM-CUR-006', quantity: 2 },
      { itemId: 'alm-10', itemName: 'Guantes Quirúrgicos 7.5', sku: 'ALM-PRO-001', quantity: 4 }
    ],
    notes: 'Cambio de apósitos catéter venoso central y vías invasivas'
  }
];

// ==============================================================================
// MÓDULO 14: ÁREA DE COMPRAS Y PROVEEDORES
// ==============================================================================

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    businessName: 'Baxter México S.A. de C.V.',
    rfc: 'BME850612KP4',
    commercialName: 'Baxter Hospitalaria',
    contactPerson: 'Lic. Mariana Villarreal Torres',
    email: 'atencion.hospitales@baxter.com',
    phone: '55-5279-7000',
    category: 'FARMACOS_SOLUCIONES',
    creditDays: 45,
    rating: 5.0,
    address: 'Av. Insurgentes Sur #1196, Benito Juárez, CDMX',
    status: 'ACTIVO'
  },
  {
    id: 'sup-2',
    businessName: 'Becton Dickinson de México S.A. de C.V.',
    rfc: 'BDM5708219H1',
    commercialName: 'BD Medical México',
    contactPerson: 'Ing. Roberto Fuentes Galindo',
    email: 'contacto.pedidos@bd.com',
    phone: '55-5999-8200',
    category: 'MATERIAL_CURACION',
    creditDays: 30,
    rating: 5.0,
    address: 'Monte Pelvoux #111, Lomas de Chapultepec, CDMX',
    status: 'ACTIVO'
  },
  {
    id: 'sup-3',
    businessName: '3M Medical Healthcare México S.A. de C.V.',
    rfc: 'TMM820304DA2',
    commercialName: '3M División Médica',
    contactPerson: 'Lic. Claudia Estrada Ruiz',
    email: 'salud.mexico@mmm.com',
    phone: '55-5270-0400',
    category: 'MATERIAL_CURACION',
    creditDays: 30,
    rating: 4.8,
    address: 'Av. Santa Fe #190, Álvaro Obregón, CDMX',
    status: 'ACTIVO'
  },
  {
    id: 'sup-4',
    businessName: 'Medtronic México S. de R.L. de C.V.',
    rfc: 'MME910408B12',
    commercialName: 'Medtronic Surgical',
    contactPerson: 'Dr. Alejandro Peña Lozano',
    email: 'ordenes.mexico@medtronic.com',
    phone: '55-5804-1500',
    category: 'EQUIPO_BIOMEDICO',
    creditDays: 60,
    rating: 4.9,
    address: 'Paseo de la Reforma #483, Cuauhtémoc, CDMX',
    status: 'ACTIVO'
  },
  {
    id: 'sup-5',
    businessName: 'Distribuidora Médica de Occidente S.A. de C.V.',
    rfc: 'DMO090415AB2',
    commercialName: 'DIMED Occidente (Guadalajara-Tepic)',
    contactPerson: 'C.P. Javier Morales Cárdenas',
    email: 'ventas@dimedoccidente.com.mx',
    phone: '33-3615-8940',
    category: 'MATERIAL_CURACION',
    creditDays: 30,
    rating: 4.7,
    address: 'Av. Vallarta #2440, Arcos Vallarta, Guadalajara, Jal.',
    status: 'ACTIVO'
  },
  {
    id: 'sup-6',
    businessName: 'Infra del Centro S.A. de C.V.',
    rfc: 'ICE780312MN9',
    commercialName: 'Grupo Infra Gases Medicinales',
    contactPerson: 'Ing. Ernesto Sánchez Godoy',
    email: 'gases.hospitalarios@infra.com.mx',
    phone: '311-213-4450',
    category: 'GASES_MEDICINALES',
    creditDays: 15,
    rating: 4.9,
    address: 'Carretera Tepic-Guadalajara Km 5, Tepic, Nayarit',
    status: 'ACTIVO'
  }
];

export const INITIAL_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'oc-1',
    orderFolio: 'OC-2026-0038',
    supplierId: 'sup-1',
    supplierName: 'Baxter México S.A. de C.V.',
    supplierRfc: 'BME850612KP4',
    requestingDepartment: 'Almacén General & Farmacia',
    orderDate: '2026-09-01',
    expectedDeliveryDate: '2026-09-04',
    paymentTerms: 'Crédito 45 días',
    subtotal: 41896.55,
    taxIva: 6703.45,
    totalAmount: 48600.00,
    status: 'SURTIDA_COMPLETA',
    authorizedBy: 'Ing. Alfonso Uribe (Administrador Único)',
    authorizedAt: '2026-09-01 11:30',
    notes: 'Surtida en Almacén con remisión BAX-98412',
    items: [
      { itemId: 'alm-7', sku: 'ALM-SOL-001', description: 'Solución Fisiológica 0.9% 1000ml (Caja c/12)', quantity: 70, unitCost: 340.00, subtotal: 23800.00 },
      { itemId: 'alm-8', sku: 'ALM-SOL-002', description: 'Solución Hartmann 1000ml (Caja c/12)', quantity: 50, unitCost: 365.00, subtotal: 18250.00 }
    ]
  },
  {
    id: 'oc-2',
    orderFolio: 'OC-2026-0041',
    supplierId: 'sup-3',
    supplierName: '3M Medical Healthcare México S.A. de C.V.',
    supplierRfc: 'TMM820304DA2',
    requestingDepartment: 'Almacén General / UCI',
    orderDate: '2026-09-06',
    expectedDeliveryDate: '2026-09-11',
    paymentTerms: 'Crédito 30 días',
    subtotal: 18491.38,
    taxIva: 2958.62,
    totalAmount: 21450.00,
    status: 'ENVIADA_PROVEEDOR',
    authorizedBy: 'Ing. Alfonso Uribe (Administrador Único)',
    authorizedAt: '2026-09-06 14:15',
    notes: 'Confirmada por ejecutivo 3M con guía DHL 77812903',
    items: [
      { itemId: 'alm-6', sku: 'ALM-CUR-006', description: 'Apósito Tegaderm 10x12 cm (Caja c/50)', quantity: 15, unitCost: 890.00, subtotal: 13350.00 },
      { itemId: 'alm-11', sku: 'ALM-PRO-002', description: 'Mascarilla N95 3M 1860 (Caja c/20)', quantity: 15, unitCost: 520.00, subtotal: 7800.00 }
    ]
  },
  {
    id: 'oc-3',
    orderFolio: 'OC-2026-0042',
    supplierId: 'sup-2',
    supplierName: 'Becton Dickinson de México S.A. de C.V.',
    supplierRfc: 'BDM5708219H1',
    requestingDepartment: 'Almacén General / Urgencias',
    orderDate: '2026-09-08',
    expectedDeliveryDate: '2026-09-13',
    paymentTerms: 'Crédito 30 días',
    subtotal: 31724.14,
    taxIva: 5075.86,
    totalAmount: 36800.00,
    status: 'PENDIENTE_AUTORIZACION',
    notes: 'Reabastecimiento preventivo mensual de insumos de punción',
    items: [
      { itemId: 'alm-1', sku: 'ALM-CUR-001', description: 'Catéter BD Insyte 18G Verde (Caja c/50)', quantity: 30, unitCost: 485.00, subtotal: 14550.00 },
      { itemId: 'alm-2', sku: 'ALM-CUR-002', description: 'Catéter BD Insyte 20G Rosa (Caja c/50)', quantity: 25, unitCost: 485.00, subtotal: 12125.00 },
      { itemId: 'alm-3', sku: 'ALM-CUR-003', description: 'Jeringa BD Plastipak 5ml (Caja c/100)', quantity: 30, unitCost: 320.00, subtotal: 9600.00 }
    ]
  },
  {
    id: 'oc-4',
    orderFolio: 'OC-2026-0043',
    supplierId: 'sup-4',
    supplierName: 'Medtronic México S. de R.L. de C.V.',
    supplierRfc: 'MME910408B12',
    requestingDepartment: 'Quirófano / Cirugía Especializada',
    orderDate: '2026-09-08',
    expectedDeliveryDate: '2026-09-15',
    paymentTerms: 'Crédito 60 días',
    subtotal: 46724.14,
    taxIva: 7475.86,
    totalAmount: 54200.00,
    status: 'PENDIENTE_AUTORIZACION',
    notes: 'Suturas y hemostáticos de alta especialidad para Laparoscopía y Cardiovascular',
    items: [
      { itemId: 'alm-5', sku: 'ALM-CUR-005', description: 'Sutura Vicryl 3-0 Trenzada (Caja c/36)', quantity: 20, unitCost: 1420.00, subtotal: 28400.00 },
      { itemId: 'ins-sut2', sku: 'ALM-CUR-008', description: 'Sutura Prolene 4-0 Cardiovascular (Caja c/36)', quantity: 15, unitCost: 1720.00, subtotal: 25800.00 }
    ]
  }
];

export const INITIAL_REQUISITIONS: PurchaseRequisition[] = [
  {
    id: 'req-1',
    requisitionFolio: 'REQ-2026-0089',
    department: 'Quirófano Central',
    requestedBy: 'Dr. Fernando Covarrubias',
    requestDate: '2026-09-08',
    urgency: 'URGENTE_DESABASTO',
    itemsDescription: '20 cajas Sutura Vicryl 3-0 y 15 cajas Prolene 4-0 cardiovascular',
    estimatedBudget: 54200.00,
    status: 'APROBADA_PARA_OC',
    linkedOrderFolio: 'OC-2026-0043',
    notes: 'Programación quirúrgica intensiva de la próxima semana'
  },
  {
    id: 'req-2',
    requisitionFolio: 'REQ-2026-0090',
    department: 'Unidad de Cuidados Intensivos (UCI)',
    requestedBy: 'Enf. Jefa Rocío Barajas',
    requestDate: '2026-09-08',
    urgency: 'NORMAL',
    itemsDescription: '25 cajas Apósito Tegaderm 10x12 y 50 circuitos de ventilador mecánico',
    estimatedBudget: 32500.00,
    status: 'PENDIENTE',
    notes: 'Consumo promedio mensual para pacientes críticos'
  },
  {
    id: 'req-3',
    requisitionFolio: 'REQ-2026-0091',
    department: 'Triage & Sala de Choque Urgencias',
    requestedBy: 'Dra. Sofía Valenzuela Ríos',
    requestDate: '2026-09-08',
    urgency: 'URGENTE_DESABASTO',
    itemsDescription: 'Catéteres 18G, Soluciones Hartmann 1000ml y jeringas 5ml/10ml',
    estimatedBudget: 36800.00,
    status: 'APROBADA_PARA_OC',
    linkedOrderFolio: 'OC-2026-0042',
    notes: 'Reposición de stock de contingencia'
  }
];

export const INITIAL_SOCIAL_WORK_CASES: SocialWorkRecord[] = [
  {
    id: 'ts-case-1',
    folio: 'TS-2026-0038',
    patientId: 'pat-2',
    patientName: 'Elena Navarro Ortiz',
    patientExpNumber: 'HPDH-2026-1043',
    patientAge: 58,
    patientGender: 'FEMENINO',
    areaService: 'HOSPITALIZACION',
    bedNumber: 'P2-204',
    caseType: 'ESTUDIO_SOCIOECONOMICO',
    status: 'APROBADO_PATRONATO',
    date: '2026-09-08',
    time: '11:30',
    socialWorkerName: 'Lic. Laura Elena Peña (Trabajadora Social)',
    familyContactName: 'Carlos Navarro Ortiz',
    familyContactRelationship: 'Hermano',
    familyContactPhone: '(311) 234-5678',
    socioeconomicLevel: 'NIVEL_2',
    familyIncomeMonthly: 12500,
    familyExpensesMonthly: 14200,
    housingType: 'RENTADA',
    familyMembersCount: 4,
    supportDiscountApprovedPercentage: 40,
    patronatoAuthorizationCode: 'PAT-2026-NVR40',
    socialDiagnosis: 'Paciente postoperada de colecistectomía por vía laparoscópica. Ingresos del núcleo familiar por debajo del costo de la atención privada. Vulnerabilidad económica alta comprobada.',
    actionsTaken: 'Se aplicó cédula socioeconómica oficial con visita a cama. Aprobado subsidio del 40% por Patronato de Beneficencia Hospitalaria para material quirúrgico y estancia.',
    notes: 'Familiar responsable notificado y conforme con el convenio de pago.'
  },
  {
    id: 'ts-case-2',
    folio: 'TS-2026-0039',
    patientId: 'pat-deceased-1',
    patientName: 'Don Salvador Vega Montaño',
    patientExpNumber: 'HPDH-2026-0982',
    patientAge: 84,
    patientGender: 'MASCULINO',
    areaService: 'UCI',
    bedNumber: 'UCI-03',
    caseType: 'TRAMITE_DEFUNCION',
    status: 'ACTA_EMITIDA',
    date: '2026-09-08',
    time: '23:45',
    socialWorkerName: 'Lic. Laura Elena Peña (Trabajadora Social)',
    familyContactName: 'Guadalupe Vega Robles',
    familyContactRelationship: 'Hija Mayor',
    familyContactPhone: '(311) 987-6543',
    deathData: {
      deathCertificateFolio: 'CERT-SSA-2026-0914',
      deathDate: '2026-09-08',
      deathTime: '23:45',
      deathCausePrimary: 'Choque cardiogénico refractario irreversible',
      deathCauseSecondary: 'Infarto Agudo al Miocardio con elevación del ST, Hipertensión Arterial Sistémica y DM2',
      certifyingPhysician: 'Dr. Fernando Covarrubias',
      certifyingPhysicianCedula: '11245980-SSA',
      legalClaimantName: 'Guadalupe Vega Robles',
      legalClaimantKinship: 'Hija Mayor',
      legalClaimantPhone: '(311) 987-6543',
      legalClaimantOfficialId: 'INE 098412894129',
      funeralHomeName: 'Funeraria San Román Tepic',
      civilRegistryFolio: 'ACTA-REG-CIVIL-2026-8812',
      civilRegistryOffice: 'Oficialía 01 del Registro Civil de Tepic',
      bodyDestination: 'INHUMACION',
      personalBelongingsDelivered: true
    },
    socialDiagnosis: 'Fallecimiento intrahospitalario por causa natural/cardiopatía senil en Unidad de Cuidados Críticos. Red familiar en duelo agudo con acompañamiento asistencial integral.',
    actionsTaken: 'Se gestionó y foliado el Certificado de Defunción SSA con el médico intensivista. Se realizó enlace con Funeraria San Román y trámite de Acta de Defunción en Oficialía 01 del Registro Civil. Pertenencias personales entregadas bajo acta formal.',
    notes: 'Liberación de restos y egreso hacia sala de velación a las 03:15 hrs sin contratiempos.'
  },
  {
    id: 'ts-case-3',
    folio: 'TS-2026-0040',
    patientId: 'pat-1',
    patientName: 'Roberto González Parra',
    patientExpNumber: 'HPDH-2026-1042',
    patientAge: 45,
    patientGender: 'MASCULINO',
    areaService: 'URGENCIAS',
    bedNumber: 'SALA_CHOQUE',
    caseType: 'CASO_MEDICO_LEGAL',
    status: 'NOTIFICADO_MP',
    date: '2026-09-08',
    time: '19:30',
    socialWorkerName: 'Lic. Laura Elena Peña (Trabajadora Social)',
    familyContactName: 'María Luisa Parra Ramos',
    familyContactRelationship: 'Madre',
    familyContactPhone: '(311) 555-0199',
    mpReportNumber: 'OF-MP-TEP-2026-0419',
    mpAgencyName: 'Fiscalía General del Estado de Nayarit - Agencia 02 de Delitos Viales',
    mpAgentName: 'Lic. Mariana Morales Orozco (M.P.)',
    mpNotificationReason: 'Hecho de tránsito vehicular terrestre con politraumatismo y estado de choque',
    mpDeliveryDate: '2026-09-08 20:10',
    socialDiagnosis: 'Paciente ingresado de extrema urgencia en Código Rojo derivado de volcadura carretera. Caso catalogado de interés médico-legal obligatorio conforme a la NOM-004 y Código Penal.',
    actionsTaken: 'Emisión inmediata del formato de notificación legal intrahospitalaria. Entrega de acuse oficial al Ministerio Público en turno y acompañamiento a familiares en sala de espera.',
    notes: 'Agente ministerial recibió reporte médico inicial y autorizó continuidad terapéutica.'
  },
  {
    id: 'ts-case-4',
    folio: 'TS-2026-0041',
    patientId: 'pat-4',
    patientName: 'Ximena Domínguez Reyes',
    patientExpNumber: 'HPDH-2026-1045',
    patientAge: 9,
    patientGender: 'FEMENINO',
    areaService: 'HOSPITALIZACION',
    bedNumber: 'P3-305',
    caseType: 'CANALIZACION_EXTERNA',
    status: 'EN_EVALUACION',
    date: '2026-09-09',
    time: '09:00',
    socialWorkerName: 'Lic. Laura Elena Peña (Trabajadora Social)',
    familyContactName: 'Patricia Reyes Alatorre',
    familyContactRelationship: 'Madre',
    familyContactPhone: '(311) 456-7890',
    referralInstitution: 'DIF Estatal Nayarit / Hospital Infantil de México Federico Gómez',
    referralReason: 'Interconsulta de tercer nivel para valoración por alta especialidad en Neumología Pediátrica Avanzada',
    ambulanceTransferRequired: true,
    socialDiagnosis: 'Menor con cuadro respiratorio de evolución tórpida. Requiere estudios complementarios de alta especialidad pediátrica no disponibles a nivel estatal.',
    actionsTaken: 'Contacto con coordinación de trabajo social del DIF Nayarit para apoyo de ambulancia de traslado de cuidados intensivos pediátricos y enlace hospitalario.',
    notes: 'En espera de confirmación de fecha de recepción en el centro receptor.'
  },
  {
    id: 'ts-case-5',
    folio: 'TS-2026-0042',
    patientId: 'pat-3',
    patientName: 'Mateo Morales Silva',
    patientExpNumber: 'HPDH-2026-1044',
    patientAge: 32,
    patientGender: 'MASCULINO',
    areaService: 'URGENCIAS',
    caseType: 'LOCALIZACION_FAMILIARES',
    status: 'CONCLUIDO',
    date: '2026-09-08',
    time: '14:20',
    socialWorkerName: 'Lic. Laura Elena Peña (Trabajadora Social)',
    familyContactName: 'Andrea Lozano Ruiz',
    familyContactRelationship: 'Cónyuge',
    familyContactPhone: '(311) 345-6789',
    socialDiagnosis: 'Paciente foráneo atendido por abdomen agudo sugestivo de apendicitis. Ingresó solo sin contacto familiar directo registrado en la ciudad.',
    actionsTaken: 'Rastreo telefónico y contacto con cónyuge en Tepic. Familiar se presentó en Admisión, firmó consentimiento informado y regularizó trámite hospitalario.',
    notes: 'Caso cerrado tras integración de la red familiar.'
  }
];
